// ============================================================
// Diagnostic v2 question bank — اختبار تحديد المستوى التشخيصي
// (نظام bac-physics-v2) لتلاميذ البكالوريا الجزائرية.
//
// Generated by scripts/build-diagnostic-v2-shuffle.js — option order is a
// deterministic, idempotent permutation (see script). Migration 011
// reconciles the seeded DB with this canonical source.
// Source of truth for all downstream consumers in this repo.
//
// Design rules (approved report):
//   * 50 أسئلة QCM، 5 مستويات صعوبة (L1..L5)
//   * لا يختبر أي مفهوم من دروس السنة الحالية:
//     أي قانون "يستحضر" السنة الحالية يُعطى داخل نص السؤال.
//   * كل مهارة في skill_map.json تُقاس بسؤالين على الأقل.
//   * كل خيار خاطئ يحمل diagnostic_error (تحليل الأخطاء).
// ============================================================

module.exports = 
{
  "test": {
    "id": "bac-physics-v2",
    "title": "اختبار تحديد المستوى التشخيصي في الفيزياء",
    "description": "اختبار تشخيصي من 50 سؤالاً لطلاب البكالوريا في الفيزياء. يقيس المكتسبات السابقة والمهارات الرياضية والفيزيائية والتفكير العلمي دون افتراض معرفة دروس السنة الحالية، ويصدر ملفاً تشخيصياً مفصلاً ومساراً تعليمياً موصى به.",
    "subject": "physics",
    "grade": "baccalaureate",
    "version": 1,
    "question_bank_version": "2026-09-bac-physics-v2",
    "total_questions": 50,
    "time_limit_minutes": 75,
    "difficulty_scale": {
      "1": "أساسي مباشر",
      "2": "تطبيق بسيط لعلاقة معطاة",
      "3": "تحليل واستغلال بيان/جدول",
      "4": "استدلال ومشكلة جديدة",
      "5": "مشكلة مركبة متعددة الخطوات"
    }
  },
  "questions": [
    {
      "id": "PHYV2-001",
      "skill": "mat-num",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit1",
        "unit2",
        "unit4"
      ],
      "question": "اكتب العدد 0.000052 بالكتابة العلمية.",
      "options": [
        {
          "id": "A",
          "text": "5.2 × 10⁻⁵",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "5.2 × 10⁻⁴",
          "diagnostic_error": "اتجاه تحريك الفاصلة خاطئ رقم واحد"
        },
        {
          "id": "C",
          "text": "52 × 10⁻⁶",
          "diagnostic_error": "كتابة غير علمية (الجزء قبل الفاصلة أكبر من 10)"
        },
        {
          "id": "D",
          "text": "5.2 × 10⁵",
          "diagnostic_error": "عكس اتجاه تحريك الفاصلة (أس موجب)"
        }
      ],
      "correct": "A",
      "explanation": "0.000052: نحرك الفاصلة 5 خانات نحو اليمين فيكون الأس −5: 5.2×10⁻⁵.",
      "diagnostic_tags": [
        "scientific_notation",
        "exponent_sign",
        "decimal_shift"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-002",
      "skill": "mat-num",
      "secondary_skill": "mat-unitconv",
      "category": "A",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit2",
        "unit4"
      ],
      "question": "قيمة 10⁻⁶ مألوفة في فيزياء الكميات الصغيرة. أي سابقة مقابلة؟",
      "options": [
        {
          "id": "A",
          "text": "نانو (n)",
          "diagnostic_error": "الخلط بين 10⁻⁶ و 10⁻⁹"
        },
        {
          "id": "B",
          "text": "ميلي (m)",
          "diagnostic_error": "الخلط بين 10⁻⁶ و 10⁻³"
        },
        {
          "id": "C",
          "text": "ميكرو (µ)",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "بيكو (p)",
          "diagnostic_error": "الخلط بين 10⁻⁶ و 10⁻¹²"
        }
      ],
      "correct": "C",
      "explanation": "السوابق: ميكرو µ=10⁻⁶، نانو n=10⁻⁹، ميلي m=10⁻³، بيكو p=10⁻¹².",
      "diagnostic_tags": [
        "si_prefix",
        "powers_of_ten"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-003",
      "skill": "mat-num",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit1",
        "unit2",
        "unit5"
      ],
      "question": "احسب: (2 × 10³) × (4 × 10⁻²)",
      "options": [
        {
          "id": "A",
          "text": "800000 (8 × 10⁵)",
          "diagnostic_error": "جمع الأسس بإشارة موجبة (3+2=5) بدل (3+(−2)=1)"
        },
        {
          "id": "B",
          "text": "80",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "8",
          "diagnostic_error": "نسيان ضرب الأعداد (2×4=8 صحيح لكن أخطأ في الأس)"
        },
        {
          "id": "D",
          "text": "800",
          "diagnostic_error": "خطأ في إشارة الأس عند الضرب"
        }
      ],
      "correct": "B",
      "explanation": "نضرب الأعداد (2×4=8) ونجمع الأسس: 10^(3+(−2))=10¹، أي 80.",
      "diagnostic_tags": [
        "multiply_powers",
        "exponent_addition"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-004",
      "skill": "mat-num",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit2",
        "unit5"
      ],
      "question": "احسب: (8 × 10⁶) ÷ (2 × 10⁻²)",
      "options": [
        {
          "id": "A",
          "text": "4 × 10⁸",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "16 × 10⁸",
          "diagnostic_error": "ضرب الأعداد بدل القسمة"
        },
        {
          "id": "C",
          "text": "4 × 10⁻⁸",
          "diagnostic_error": "خطأ في إشارة الأس الناتج"
        },
        {
          "id": "D",
          "text": "4 × 10⁴",
          "diagnostic_error": "جمع الأسس بدلاً من طرحها (6−2 بدل 6+2)"
        }
      ],
      "correct": "A",
      "explanation": "8÷2=4 وللقسمة نطرح الأسس: 10^(6−(−2))=10⁸، أي 4×10⁸.",
      "diagnostic_tags": [
        "divide_powers",
        "exponent_subtraction"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-005",
      "skill": "mat-unitconv",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit1",
        "unit5"
      ],
      "question": "حوّل 72 km/h إلى m/s.",
      "options": [
        {
          "id": "A",
          "text": "259.2 m/s",
          "diagnostic_error": "ضرب بـ 3.6 بدل القسمة"
        },
        {
          "id": "B",
          "text": "36 m/s",
          "diagnostic_error": "القسمة على 2 بدل 3.6"
        },
        {
          "id": "C",
          "text": "20 m/s",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "72 m/s",
          "diagnostic_error": "عدم التحويل (ترك الوحدة) والنظام غير SI"
        }
      ],
      "correct": "C",
      "explanation": "التحويل من km/h إلى m/s يكون بالقسمة على 3.6: 72/3.6 = 20 m/s.",
      "diagnostic_tags": [
        "speed_conversion",
        "kmh_to_ms"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-006",
      "skill": "mat-unitconv",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "ما قيمة 250 cm³ بوحدة اللتر (L)؟",
      "options": [
        {
          "id": "A",
          "text": "0.25 L",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "25 L",
          "diagnostic_error": "الاعتقاد أن 1 L = 10 cm³"
        },
        {
          "id": "C",
          "text": "2.5 L",
          "diagnostic_error": "الخلط بين cm³ و mL"
        },
        {
          "id": "D",
          "text": "250000 L",
          "diagnostic_error": "عكس اتجاه التحويل (ضرب بـ 1000 بدل قسمته)"
        }
      ],
      "correct": "A",
      "explanation": "1 L = 1 dm³ = 1000 cm³، إذن 250 cm³ = 250/1000 = 0.25 L.",
      "diagnostic_tags": [
        "volume_conversion",
        "liter_cm3"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-007",
      "skill": "mat-unitconv",
      "secondary_skill": "mat-num",
      "category": "A",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "عبر عن 1.66 × 10⁻²⁷ kg (كتلة الوحدة الذرية تقريباً) بالميجاغرام (Mg) علمياً نتائجك بالكتابة العلمية.",
      "options": [
        {
          "id": "A",
          "text": "1.66 × 10⁹ Mg",
          "diagnostic_error": "عكس اتجاه التحويل"
        },
        {
          "id": "B",
          "text": "1.66 × 10⁻²⁷ Mg",
          "diagnostic_error": "عدم اعتبار معامل التحويل (اعتبر kg = Mg)"
        },
        {
          "id": "C",
          "text": "1.66 × 10⁻²⁴ Mg",
          "diagnostic_error": "استعمال 10³ بدل 10⁶"
        },
        {
          "id": "D",
          "text": "1.66 × 10⁻³⁰ Mg",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "1 Mg = 10⁶ g = 10³ kg، إذن 1.66×10⁻²⁷ kg = 1.66×10⁻²⁷ / 10³ = 1.66×10⁻³⁰ Mg.",
      "diagnostic_tags": [
        "mass_conversion",
        "prefix_10_6"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-008",
      "skill": "mat-unitconv",
      "secondary_skill": "mat-algebra",
      "category": "A",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "في العلاقات النووية يواجه المتعلم تحويلات مثل: 1 uma = 1.66054×10⁻²⁷ kg و 1 eV = 1.6×10⁻¹⁹ J. باستعمال علاقة التكافؤ E = m·c²، عبر عن 1 uma بوحدة MeV (علماً أن 1 MeV = 10⁶ eV، و c² ≈ 9×10¹⁶ m²/s²).",
      "options": [
        {
          "id": "A",
          "text": "≈ 931 × 10⁶ MeV",
          "diagnostic_error": "عدم القسمة على 10⁶ بعد التحويل إلى eV"
        },
        {
          "id": "B",
          "text": "≈ 9.31×10⁻¹⁰ MeV",
          "diagnostic_error": "الخلط بين التحويل إلى J والتحويل إلى MeV"
        },
        {
          "id": "C",
          "text": "≈ 931 MeV",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "≈ 9.31 MeV",
          "diagnostic_error": "النقص بعامل 10² في الحساب"
        }
      ],
      "correct": "C",
      "explanation": "E = m·c² = 1.66054×10⁻²⁷ × 9×10¹⁶ ≈ 1.4945×10⁻¹⁰ J، ثم نحول إلى eV بقسمة 1.6×10⁻¹⁹: ≈ 9.34×10⁸ eV ≈ 934 MeV ≈ 931 MeV.",
      "diagnostic_tags": [
        "energy_conversion",
        "amu_mev",
        "c_squared"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-009",
      "skill": "mat-algebra",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit1",
        "unit2",
        "unit3",
        "unit4",
        "unit5"
      ],
      "question": "من العلاقة n = m/M، عبر عن الكتلة m.",
      "options": [
        {
          "id": "A",
          "text": "m = M / n",
          "diagnostic_error": "قلب العلاقة (القسمة المعكوسة)"
        },
        {
          "id": "B",
          "text": "m = n / M",
          "diagnostic_error": "اعتبار n محلّى مباشرة بدون عزل"
        },
        {
          "id": "C",
          "text": "m = M − n",
          "diagnostic_error": "خلط الجبر (الجمع بدل الضرب)"
        },
        {
          "id": "D",
          "text": "m = n × M",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "n = m/M ⇒ اضرب الطرفين في M: m = n × M.",
      "diagnostic_tags": [
        "isolate_variable",
        "multiply_both_sides"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-010",
      "skill": "mat-algebra",
      "secondary_skill": "mat-logexp",
      "category": "A",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "من العلاقة t½ = ln2/λ، عبر عن ثابت التفكك λ.",
      "options": [
        {
          "id": "A",
          "text": "λ = t½ × ln2",
          "diagnostic_error": "اعتبار الجداء بدل القسمة"
        },
        {
          "id": "B",
          "text": "λ = ln2 / t½",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "λ = t½ / ln2",
          "diagnostic_error": "قلب النسبة (البسط والمقام انعكسا)"
        },
        {
          "id": "D",
          "text": "λ = ln2 × t½",
          "diagnostic_error": "عدم إعادة (الضرب لكن بتعويض خاطئ)"
        }
      ],
      "correct": "B",
      "explanation": "t½ = ln2/λ ⇒ بضرب الطرفين في λ: λ·t½ = ln2 ⇒ λ = ln2/t½.",
      "diagnostic_tags": [
        "isolate_variable",
        "fraction_solve"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-011",
      "skill": "mat-algebra",
      "secondary_skill": "mat-proportion",
      "category": "A",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "علاقة التمديد: C₁·V₁ = C₂·V₂، ومعامل التمديد F = C₁/C₂. عبر عن F بدلالة الحجمين فقط.",
      "options": [
        {
          "id": "A",
          "text": "F = V₁ × V₂",
          "diagnostic_error": "جداء الحجوم بدل القسمة"
        },
        {
          "id": "B",
          "text": "F = V₂ − V₁",
          "diagnostic_error": "طرح الحجوم بدل قسمتها"
        },
        {
          "id": "C",
          "text": "F = V₂ / V₁",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "F = V₁ / V₂",
          "diagnostic_error": "قلب النسبة في تعويض C₁/C₂"
        }
      ],
      "correct": "C",
      "explanation": "من C₁V₁=C₂V₂ نجد C₁/C₂ = V₂/V₁، أي F = V₂/V₁.",
      "diagnostic_tags": [
        "rearrange",
        "ratio_conversion"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-012",
      "skill": "mat-algebra",
      "secondary_skill": "mat-num",
      "category": "A",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "السرعة المدارية لقمر: v = √(G·M/r) مع G = 6.67×10⁻¹¹ (وحدات SI) و M = 6×10²⁴ kg و r = 4×10⁷ m. احسب v (بالتقريب).",
      "options": [
        {
          "id": "A",
          "text": "≈ 316 m/s",
          "diagnostic_error": "خطأ في حساب الجذر (ناقص صفر)"
        },
        {
          "id": "B",
          "text": "≈ 3160 m/s",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "≈ 10⁷ m/s",
          "diagnostic_error": "نسيان الجذر التربيعي"
        },
        {
          "id": "D",
          "text": "≈ 100 m/s",
          "diagnostic_error": "خطأ في قوى العدد 10 داخل المقدار"
        }
      ],
      "correct": "B",
      "explanation": "G·M/r = (6.67×10⁻¹¹ × 6×10²⁴)/4×10⁷ = 4×10¹³/4×10⁷ = 10⁶، وجذر 10⁶ = 10³، مع 6.67×6/4 ≈ 10، أي v ≈ √(10×10⁶) ≈ 3160 m/s.",
      "diagnostic_tags": [
        "square_root",
        "combine_powers",
        "orbital_speed"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-013",
      "skill": "mat-proportion",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit1",
        "unit4"
      ],
      "question": "25% من كمية مقدارها 80 mol تساوي:",
      "options": [
        {
          "id": "A",
          "text": "55 mol",
          "diagnostic_error": "حساب المتبقي بدل النسبة"
        },
        {
          "id": "B",
          "text": "25 mol",
          "diagnostic_error": "اعتبار النسبة كمية مباشرة"
        },
        {
          "id": "C",
          "text": "20 mol",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "4 mol",
          "diagnostic_error": "قسمة 80 على 25 بدل الضرب في 0.25"
        }
      ],
      "correct": "C",
      "explanation": "25% = 0.25، إذن 0.25 × 80 = 20 mol.",
      "diagnostic_tags": [
        "percentage",
        "multiplication"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-014",
      "skill": "mat-proportion",
      "secondary_skill": "phy-lawapply",
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "قانون التناقص الإشعاعي: إذا بقي بعد مرور زمن t نصفُ العدد الابتدائي فقط (N = N₀/2)، فما النسبة المئوية المتبقية بعد مرور زمن 2t؟ (الانحلال متكرر بنصفين)",
      "options": [
        {
          "id": "A",
          "text": "75%",
          "diagnostic_error": "اعتبار المتبقي يزداد نسبةً خطية"
        },
        {
          "id": "B",
          "text": "0%",
          "diagnostic_error": "اعتبار الانحلال خطياً (ينفد تماماً)"
        },
        {
          "id": "C",
          "text": "25%",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "50%",
          "diagnostic_error": "عدم تكرار التنصيف (تطبيق نصف واحد فقط)"
        }
      ],
      "correct": "C",
      "explanation": "كل نصف عمر يبقي النصف: بعد 2t يبقى ½×½ = ¼ = 25%.",
      "diagnostic_tags": [
        "halving",
        "repeated_ratio"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-015",
      "skill": "mat-proportion",
      "secondary_skill": "mat-algebra",
      "category": "A",
      "difficulty": 3,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit4"
      ],
      "question": "جدول التقدم لتفاعل: A تأهباً، n(A) = n₀ − x. إذا كانت كمية المادة الابتدائية n₀ = 0.4 mol والمتقدم النهائي x_f = 0.3 mol، فما نسبة التقدم النهائي τf = x_f/x_max إذا كان x_max = 0.4 mol؟",
      "options": [
        {
          "id": "A",
          "text": "0.25",
          "diagnostic_error": "حساب (0.4−0.3)/0.4 بدل x_f/x_max"
        },
        {
          "id": "B",
          "text": "0.75",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "1.33",
          "diagnostic_error": "قلب النسبة (x_max/x_f)"
        },
        {
          "id": "D",
          "text": "0.3",
          "diagnostic_error": "استعمال x_f وحده بدل النسبة"
        }
      ],
      "correct": "B",
      "explanation": "τf = x_f/x_max = 0.3/0.4 = 0.75.",
      "diagnostic_tags": [
        "advancement_ratio",
        "fraction"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-016",
      "skill": "mat-proportion",
      "secondary_skill": "phy-graph",
      "category": "A",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "قانون كبلر الثالث: T² = k·r³ (r نصف المحور الأكبر). إذا تضاعف نصف المحور r، فكيف يتغير الزمن الدوري T؟",
      "options": [
        {
          "id": "A",
          "text": "يتضاعف بنحو 2.8 (× 2√2)",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "لا يتغير",
          "diagnostic_error": "تجاهل اعتماد T على r"
        },
        {
          "id": "C",
          "text": "يتضاعف أربع مرات (×4)",
          "diagnostic_error": "الخلط بين T² و T"
        },
        {
          "id": "D",
          "text": "يتضاعف تماماً (×2)",
          "diagnostic_error": "اعتبار T∝r مباشرة بدون الجذر"
        }
      ],
      "correct": "A",
      "explanation": "T = √(k·r³): إذا تضاعف r يصبح T' = √(k·(2r)³) = √(8·k·r³) = √8 · T ≈ 2.83 T.",
      "diagnostic_tags": [
        "power_law",
        "cube_root_behaviour"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-017",
      "skill": "mat-logexp",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit2",
        "unit4"
      ],
      "question": "احسب ln(e²) ثم ln(1).",
      "options": [
        {
          "id": "A",
          "text": "0 ثم 2",
          "diagnostic_error": "عكس الموضعين (التبديل)"
        },
        {
          "id": "B",
          "text": "2 ثم 0",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "e² ثم 1",
          "diagnostic_error": "الخلط بين الدالة وعكسها"
        },
        {
          "id": "D",
          "text": "2 ثم 1",
          "diagnostic_error": "الاعتقاد ln(1) = 1"
        }
      ],
      "correct": "B",
      "explanation": "ln(e^x) = x، إذن ln(e²) = 2، و ln(1) = 0 لأن e⁰ = 1.",
      "diagnostic_tags": [
        "natural_log",
        "inverse_exp"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-018",
      "skill": "mat-logexp",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit4"
      ],
      "question": "علاقة pH = −log[H₃O⁺]. محاليل مائية نقي التركيز [H₃O⁺] = 0.001 mol/L و [OH⁻] معه. احسب pH (لاحظ log(10⁻³) = −3).",
      "options": [
        {
          "id": "A",
          "text": "pH = 11",
          "diagnostic_error": "حساب pOH بدل pH"
        },
        {
          "id": "B",
          "text": "pH = 0.001",
          "diagnostic_error": "إرجاع التركيز مباشرة دون لوغاريتم"
        },
        {
          "id": "C",
          "text": "pH = 3",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "pH = −3",
          "diagnostic_error": "الخلط بين pH و[H₃O⁺] بعلامة"
        }
      ],
      "correct": "C",
      "explanation": "pH = −log(10⁻³) = −(−3) = 3.",
      "diagnostic_tags": [
        "ph_scale",
        "log10_scale"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-019",
      "skill": "mat-logexp",
      "secondary_skill": "rea-justify",
      "category": "A",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit2",
        "unit3",
        "unit5"
      ],
      "question": "مقدار يتناقص أسياً: y(t) = y₀·e^(−t/τ). عند اللحظة t = τ، ما قيمة y بالعلاقة مع y₀ (تذكر eⁿ ≈ 2.72)؟",
      "options": [
        {
          "id": "A",
          "text": "y ≈ y₀ / 2.72 (أي ≈ 0.37 y₀)",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "y = 0",
          "diagnostic_error": "اعتبار التناقص الأسّي وصولاً للصفر عند t=τ"
        },
        {
          "id": "C",
          "text": "y = y₀ / 2",
          "diagnostic_error": "الخلط مع نصف العمر (الأس × ln2)"
        },
        {
          "id": "D",
          "text": "y = y₀",
          "diagnostic_error": "اعتبار e^(−1) قريب من 1"
        }
      ],
      "correct": "A",
      "explanation": "y(τ) = y₀·e^(−1) = y₀/e ≈ y₀/2.72 ≈ 0.37 y₀. (هذا أصل طريقة 37% في تفريغ المكثفة).",
      "diagnostic_tags": [
        "exponential_decay",
        "tau_37_percent"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-020",
      "skill": "mat-logexp",
      "secondary_skill": "mat-algebra",
      "category": "A",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "قانون التفكك: N(t) = N₀·e^(−λt). تريد حساب زمن التأريخ t حيث يبقى N = N₀/4. عبر عن t (استعمل ln).",
      "options": [
        {
          "id": "A",
          "text": "t = ln(1/4) / λ = −ln4/λ",
          "diagnostic_error": "علامة سالبة في البسط رغم أن t زمن موجب"
        },
        {
          "id": "B",
          "text": "t = ln(4/1) · λ",
          "diagnostic_error": "خلط بين ln والضرب في λ"
        },
        {
          "id": "C",
          "text": "t = ln4 / λ",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "t = λ · ln4",
          "diagnostic_error": "لا عزل صحيح (المقام والبسط انقلبا)"
        }
      ],
      "correct": "C",
      "explanation": "N₀/4 = N₀e^(−λt) ⇒ e^(−λt) = 1/4 ⇒ −λt = ln(1/4) = −ln4 ⇒ t = ln4/λ.",
      "diagnostic_tags": [
        "logarithm_solve",
        "decay_dating"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-021",
      "skill": "mat-calc",
      "secondary_skill": "phy-graph",
      "category": "A",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit1",
        "unit5"
      ],
      "question": "ما اشتقاق الدالة x(t) = 5t + 3 بالنسبة للزمن t؟",
      "options": [
        {
          "id": "A",
          "text": "dx/dt = 5t²/2 + 3t",
          "diagnostic_error": "التكامل بدل الاشتقاق (قاعدة معكوسة)"
        },
        {
          "id": "B",
          "text": "dx/dt = 5",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "dx/dt = 5t",
          "diagnostic_error": "نسيان أن اشتقاق t يساوي 1"
        },
        {
          "id": "D",
          "text": "dx/dt = 5 + 3t",
          "diagnostic_error": "اشتقاق الثابت 3 كأنه متغير"
        }
      ],
      "correct": "B",
      "explanation": "اشتقاق 5t هو 5 (ثابت)، واشتقاق الثابت 3 هو 0: النتيجة 5.",
      "diagnostic_tags": [
        "derivative_polynomial",
        "constant_rule"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-022",
      "skill": "mat-calc",
      "secondary_skill": "phy-graph",
      "category": "A",
      "difficulty": 3,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "سرعة التفاعل في المتابعة الزمنية هي v = dx/dt. إذا كان المنحنى x(t) مماسٌ له ميل يساوي 0.02 mol/s عند اللحظة t₀، فما معنى هذه القيمة؟",
      "options": [
        {
          "id": "A",
          "text": "السرعة المتوسطة على كامل التجربة",
          "diagnostic_error": "الخلط بين السرعة اللحظية والمتوسطة"
        },
        {
          "id": "B",
          "text": "السرعة اللحظية للتفاعل عند t₀ = 0.02 mol/s",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "زمن نصف التفاعل 0.02 s",
          "diagnostic_error": "خلط وحدات الميل مع زمن"
        },
        {
          "id": "D",
          "text": "التقدم المنجز حتى t₀ هو 0.02 mol",
          "diagnostic_error": "خلط الميل مع قيمة x نفسها"
        }
      ],
      "correct": "B",
      "explanation": "ميل المماس لمنحنى x(t) عند لحظة يعطي قيمة المشتقة dx/dt أي السرعة اللحظية عند تلك اللحظة.",
      "diagnostic_tags": [
        "slope_meaning",
        "instantaneous_rate"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-023",
      "skill": "mat-calc",
      "secondary_skill": "phy-graph",
      "category": "A",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "من جملة السرعة: v(t) = 2t + 1 (m/s). ما المسافة المقطوعة بين t = 0 و t = 3 s؟ (المسافة = مساحة سطح تحت منحنى v(t)، والناتج بالتكامل)",
      "options": [
        {
          "id": "A",
          "text": "18 m",
          "diagnostic_error": "التكامل مع نسيان الثابت (استعمال 2t² وحده)"
        },
        {
          "id": "B",
          "text": "12 m",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "7 m",
          "diagnostic_error": "حساب v(3) فقط بدل المساحة"
        },
        {
          "id": "D",
          "text": "6 m",
          "diagnostic_error": "حساب مساحة مستطيل (سرعة متوسطة مفترضة)"
        }
      ],
      "correct": "B",
      "explanation": "المسافة = ∫₀³(2t+1)dt = [t²+t]₀³ = 9+3 = 12 m.",
      "diagnostic_tags": [
        "definite_integral",
        "area_under_curve"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-024",
      "skill": "mat-vectrig",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "مركبتا شعاع السرعة: vx = 6 m/s و vy = 8 m/s. احسب معيار السرعة |v| = √(vx² + vy²).",
      "options": [
        {
          "id": "A",
          "text": "2 m/s",
          "diagnostic_error": "الفرق بين المركبتين (8−6)"
        },
        {
          "id": "B",
          "text": "48 m/s",
          "diagnostic_error": "الضرب قبل الجذر (6×8)"
        },
        {
          "id": "C",
          "text": "14 m/s",
          "diagnostic_error": "جمع المركبتين مباشرة (6+8)"
        },
        {
          "id": "D",
          "text": "10 m/s",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "|v| = √(36+64) = √100 = 10 m/s.",
      "diagnostic_tags": [
        "vector_magnitude",
        "pythagoras"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-025",
      "skill": "mat-vectrig",
      "secondary_skill": null,
      "category": "A",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "شعاع سرعة مقدار v₀ = 20 m/s مُمال بزاوية α = 60° مع الأفقي. احسب المركبة العمودية v₀·sin(60°) (تذكر sin60° ≈ 0.87).",
      "options": [
        {
          "id": "A",
          "text": "≈ 34.6 m/s",
          "diagnostic_error": "ضرب خاطئ (20 × 1.73)"
        },
        {
          "id": "B",
          "text": "≈ 20 m/s",
          "diagnostic_error": "اعتبار المركبة تساوي المعيار مباشرة"
        },
        {
          "id": "C",
          "text": "≈ 17.3 m/s",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "≈ 10 m/s",
          "diagnostic_error": "استعمال cos60° بدل sin60° (المركبة الأفريقية)"
        }
      ],
      "correct": "C",
      "explanation": "v₀z = v₀·sin60° = 20 × 0.87 ≈ 17.3 m/s.",
      "diagnostic_tags": [
        "sine_projection",
        "oblique_throw"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-026",
      "skill": "mat-vectrig",
      "secondary_skill": "phy-lawapply",
      "category": "A",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "على مستوي مائل بزاوية α مع الأفقي، يُسقط وزن جسم P على المحور الموازي للمستوي فيعطي المركبة P·sinα. إذا كان P = 100 N و α = 30° (sin30° = 0.5)، فما قيمة هذه المركبة؟",
      "options": [
        {
          "id": "A",
          "text": "50 N",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "100 N",
          "diagnostic_error": "اعتبار المركبة تساوي الوزن (زاوية 90°) للخطأ"
        },
        {
          "id": "C",
          "text": "12.5 N",
          "diagnostic_error": "جداء خاطئ (100 × 0.5 / 4)"
        },
        {
          "id": "D",
          "text": "86.6 N",
          "diagnostic_error": "استعمال cos30° بدل sin30°"
        }
      ],
      "correct": "A",
      "explanation": "P·sinα = 100 × 0.5 = 50 N — هذا أصل حركة جسم فوق مستوي مائل.",
      "diagnostic_tags": [
        "inclined_plane",
        "inclined_plane_component"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-027",
      "skill": "phy-graph",
      "secondary_skill": "mat-calc",
      "category": "B",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1",
        "unit5"
      ],
      "question": "منحنى x(t) لحركة مستقيمة هو خط مستقيم يمر بالنقطتين (2, 8) و(6, 20) مع x بالمتر وt بالثانية. ما ميل الخط (أي السرعة الثابتة)؟",
      "options": [
        {
          "id": "A",
          "text": "12 m/s",
          "diagnostic_error": "استعمال Δx فقط دون القسمة على Δt"
        },
        {
          "id": "B",
          "text": "3 m/s",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "2 m/s",
          "diagnostic_error": "خطأ حسابي في الفرق (20−8=12، ÷(6−2)=4)"
        },
        {
          "id": "D",
          "text": "4 m/s",
          "diagnostic_error": "حساب الميل كما Δx/Δt لكن أخطأ في الفرقة (8/2)"
        }
      ],
      "correct": "B",
      "explanation": "الميل = (20−8)/(6−2) = 12/4 = 3 m/s.",
      "diagnostic_tags": [
        "linear_slope",
        "speed_from_graph"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-028",
      "skill": "phy-graph",
      "secondary_skill": null,
      "category": "B",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "لاختيار طريقة بيانية بديلة، نرسم ln(N) بدلالة t فنجد خطاً مستقيماً. إذا كان الميل = −0.04 (وحدة s⁻¹)، فما قيمة ثابت التفكك λ (بعلاقة N = N₀e^(−λt))؟",
      "options": [
        {
          "id": "A",
          "text": "λ = −0.04 s⁻¹",
          "diagnostic_error": "الجمع المباشر للعلامة السالبة في λ"
        },
        {
          "id": "B",
          "text": "λ = e^0.04 s⁻¹",
          "diagnostic_error": "الخلط بين ln والتجزيء"
        },
        {
          "id": "C",
          "text": "λ = 1/0.04 s⁻¹",
          "diagnostic_error": "قلب العلاقة (اعتبار tan(θ)=1/λ)"
        },
        {
          "id": "D",
          "text": "λ = 0.04 s⁻¹",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "بأخذ ln: lnN = lnN₀ − λt، فميل المستقيم = −λ، إذن λ = 0.04 s⁻¹.",
      "diagnostic_tags": [
        "linearization",
        "ln_graph_slope"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-029",
      "skill": "phy-graph",
      "secondary_skill": "mat-logexp",
      "category": "B",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit3"
      ],
      "question": "منحنى شحن مكثفة uC(t) يقترب أسياً من القيمة النهائية E. عند الزمن المقابل لـ τ (ثابت الزمن) يصل uC إلى 63% من E. إذا كان E = 12 V و τ = 2 s، فماذا تكون uC عند t = 2 s تقريباً؟",
      "options": [
        {
          "id": "A",
          "text": "≈ 4.4 V",
          "diagnostic_error": "حساب 37% بدل 63% (خلط شحن/تفريغ)"
        },
        {
          "id": "B",
          "text": "≈ 7.6 V",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "≈ 12 V",
          "diagnostic_error": "التوصل للقيمة النهائية فوراً (اعتبار τ = ∞)"
        },
        {
          "id": "D",
          "text": "≈ 0 V",
          "diagnostic_error": "اعتبار المكثفة فارغة عند τ"
        }
      ],
      "correct": "B",
      "explanation": "عند t = τ: uC = 0.63 × E = 0.63 × 12 ≈ 7.6 V.",
      "diagnostic_tags": [
        "time_constant_63",
        "rc_charging_curve"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-030",
      "skill": "phy-graph",
      "secondary_skill": "phy-table",
      "category": "B",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "منحنى v(t) للسقوط الحر v = 10t (m/s). المسافة المقطوعة خلال أول 5 ثوانٍ تساوي مساحة سطح تحت المنحنى وهي سطح مثلث. احسبها.",
      "options": [
        {
          "id": "A",
          "text": "250 m",
          "diagnostic_error": "مساحة المثلث بضرب القاعدة × الارتفاع بدون قسمة (×2)"
        },
        {
          "id": "B",
          "text": "50 m",
          "diagnostic_error": "مساحة المستطيل (القاعدة × العرض كأن v ثابتة)"
        },
        {
          "id": "C",
          "text": "10 m",
          "diagnostic_error": "استخلاص الارتفاع الواحد (v(1) فقط)"
        },
        {
          "id": "D",
          "text": "125 m",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "المساحة = ½ × القاعدة(5s) × الارتفاع(v(5)=50 m/s) = ½×5×50 = 125 m.",
      "diagnostic_tags": [
        "triangle_area",
        "distance_from_v_t"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-031",
      "skill": "phy-table",
      "secondary_skill": null,
      "category": "B",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "جدول تتبع زمني لتحول كيميائي يعطي x (mmol) عند لحظات t (min): t=0→0، t=1→20، t=2→35، t=3→44، t=4→48، t=5→49. أي استنتاج صحيح؟",
      "options": [
        {
          "id": "A",
          "text": "السرعة تتناقص مع الزمن حتى تقارب الصفر",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "السرعة ثابتة طوال التفاعل",
          "diagnostic_error": "عدم ملاحظة تناقص زيادات x"
        },
        {
          "id": "C",
          "text": "السرعة تزداد مع الزمن",
          "diagnostic_error": "خلط زيادة x مع زيادة السرعة"
        },
        {
          "id": "D",
          "text": "التفاعل سريع جداً وينتهي عند t=1",
          "diagnostic_error": "اعتبار أول خطوة كل شيء"
        }
      ],
      "correct": "A",
      "explanation": "الزيادات (20، 15، 9، 4، 1) تتناقص: السرعة (= التغير) تتناقص حتى تقارب الصفر قرب النهاية.",
      "diagnostic_tags": [
        "table_pattern",
        "rate_decrease"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-032",
      "skill": "phy-table",
      "secondary_skill": "mat-proportion",
      "category": "B",
      "difficulty": 3,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "جدول التصوير المتعاقب لمتحرك يعطي المواضع عند فواصل زمنية ثابتة τ = 0.1 s: M0(0)، M1(0.01)، M2(0.04)، M3(0.09)، M4(0.16) بالمتر. ما طبيعة الحركة (يتصاعد الفارق بانتظام)؟",
      "options": [
        {
          "id": "A",
          "text": "حركة دائرية",
          "diagnostic_error": "لا يمكن استنتاج من البيانات (إسقاط خاطئ)"
        },
        {
          "id": "B",
          "text": "حركة متباطئة",
          "diagnostic_error": "عكس الاتجاه (خلط التسارع مع التباطؤ)"
        },
        {
          "id": "C",
          "text": "حركة متسارعة بانتظام",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "حركة منتظمة",
          "diagnostic_error": "عدم ملاحظة تصاعد الفوارق"
        }
      ],
      "correct": "C",
      "explanation": "الأبعاد تتزايد بفرق: 0.01، 0.03، 0.05، 0.07 — الزيادة في كل فترة ثابتة (0.02) ⇒ تسارع ثابت ⇒ حركة متسارعة بانتظام.",
      "diagnostic_tags": [
        "sequential_frames",
        "uniform_acceleration"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-033",
      "skill": "phy-unitsdim",
      "secondary_skill": "mat-unitconv",
      "category": "B",
      "difficulty": 2,
      "estimated_time": 45,
      "prerequisite_lessons": [
        "unit3"
      ],
      "question": "باعتماد أن R تقاس بالأوم (Ω) و C بالفاراد (F)، وأن الجداء R·C يُستخدم كثابت زمن. ما وحدة الجداء R·C في النظام الدولي؟",
      "options": [
        {
          "id": "A",
          "text": "الهيرتز (Hz)",
          "diagnostic_error": "الخلط بين الزمن والتردد"
        },
        {
          "id": "B",
          "text": "بلا أبعاد تماماً",
          "diagnostic_error": "الاعتقاد أنه مجرد عدد"
        },
        {
          "id": "C",
          "text": "الثانية (s)",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "الفولت (V)",
          "diagnostic_error": "خلط وحدات التوتر"
        }
      ],
      "correct": "C",
      "explanation": "التحليل البعدي: 1 Ω = 1 kg·m²/(A²·s³) و 1 F = 1 A²·s⁴/(kg·m²)، والجداء = s. أي [R·C] = [T].",
      "diagnostic_tags": [
        "dimensional_homogeneity",
        "rc_time_constant"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-034",
      "skill": "phy-unitsdim",
      "secondary_skill": "mat-logexp",
      "category": "B",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "نشاط مصدر مشع A = λ·N حيث λ ثابت تفكك وN عدد الأنوية (بدون وحدة). إذا قيس النشاط بـ Bq = تفكك/ثانية، فما وحدة λ؟",
      "options": [
        {
          "id": "A",
          "text": "جول (J)",
          "diagnostic_error": "خلط وحدات الطاقة"
        },
        {
          "id": "B",
          "text": "Bq",
          "diagnostic_error": "الخلط بين النشاط وثابت التفكك"
        },
        {
          "id": "C",
          "text": "s⁻¹",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "s",
          "diagnostic_error": "الاعتقاد λ زمن (خلط مع τ=1/λ)"
        }
      ],
      "correct": "C",
      "explanation": "λ = A/N: وحدة النشاط على عدد بلا وحدة ⇒ وحدة λ هي s⁻¹.",
      "diagnostic_tags": [
        "unit_inference",
        "activity_law"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-035",
      "skill": "phy-unitsdim",
      "secondary_skill": "mat-algebra",
      "category": "B",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "قوة الاحتكاك f = K·v حيث v سرعة (m/s) و f قوة (N). بالتحليل البعدي، ما وحدة الثابت K في النظام الدولي؟ (N = kg·m/s²)",
      "options": [
        {
          "id": "A",
          "text": "kg·m/s²",
          "diagnostic_error": "وحدة القوة نفسها (نسيان القسمة على السرعة)"
        },
        {
          "id": "B",
          "text": "kg/s",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "بلا وحدات",
          "diagnostic_error": "اعتبار K عدداً صرفاً"
        },
        {
          "id": "D",
          "text": "kg·m/s",
          "diagnostic_error": "قسمة على v² بدل v"
        }
      ],
      "correct": "B",
      "explanation": "K = f/v: (kg·m/s²)/(m/s) = kg/s.",
      "diagnostic_tags": [
        "viscous_force",
        "derive_unit_from_formula"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-036",
      "skill": "phy-lawapply",
      "secondary_skill": null,
      "category": "B",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "علاقة التركيز: C = n/V مع n = 1 mol و V = 2 L. احسب C.",
      "options": [
        {
          "id": "A",
          "text": "3 mol/L",
          "diagnostic_error": "جمع بدل قسمة"
        },
        {
          "id": "B",
          "text": "1 mol/L",
          "diagnostic_error": "استعمال n وحده دون القسمة على الحجم"
        },
        {
          "id": "C",
          "text": "2 mol/L",
          "diagnostic_error": "قلب النسبة (C = V/n)"
        },
        {
          "id": "D",
          "text": "0.5 mol/L",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "توظيف مباشر: C = 1/2 = 0.5 mol/L.",
      "diagnostic_tags": [
        "apply_relation",
        "molar_concentration"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-037",
      "skill": "phy-lawapply",
      "secondary_skill": "mat-unitconv",
      "category": "B",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "قانون الغازات: n = P·V/(R·T) حيث P بالباسكال و V بالمتر³ و T بالكلفن. احسب n لكتلة غاز حيث P = 10⁵ Pa، V = 0.024 m³، T = 300 K، R = 8.31 J/(mol·K).",
      "options": [
        {
          "id": "A",
          "text": "n ≈ 960 mol",
          "diagnostic_error": "عدم القسمة على R·T (حساب P·V فقط)"
        },
        {
          "id": "B",
          "text": "n ≈ 1.6 mol",
          "diagnostic_error": "استعمال درجة الحرارة بالسلسيوس دون تحويل"
        },
        {
          "id": "C",
          "text": "n ≈ 1.04 × 10⁻² mol",
          "diagnostic_error": "خطأ في العمود (ضرب T في R صحيح لكن مقام خاطئ)"
        },
        {
          "id": "D",
          "text": "n ≈ 0.96 mol",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "n = (10⁵ × 0.024) / (8.31 × 300) = 2400 / 2493 ≈ 0.96 mol.",
      "diagnostic_tags": [
        "ideal_gas",
        "substitute_units"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-038",
      "skill": "phy-lawapply",
      "secondary_skill": "mat-proportion",
      "category": "B",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit4"
      ],
      "question": "قانون المعايرة عند التكافؤ: Ca·Va = Cb·Vb. إذا كان Ca = 0.1 mol/L، Va = 20 mL، Cb = 0.05 mol/L، فما حجم الأساس Vb عند التكافؤ؟",
      "options": [
        {
          "id": "A",
          "text": "100 mL",
          "diagnostic_error": "نسيان التحويل إلى mL وعمل 0.1×20/0.05×1000"
        },
        {
          "id": "B",
          "text": "10 mL",
          "diagnostic_error": "خطأ في قلب النسبة (Vb = Ca·Cb·Va خطأ)"
        },
        {
          "id": "C",
          "text": "40 mL",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "20 mL",
          "diagnostic_error": "اعتبار Vb = Va (تجاهل تركيز Cb)"
        }
      ],
      "correct": "C",
      "explanation": "Vb = Ca·Va/Cb = (0.1 × 20)/0.05 = 2/0.05 = 40 mL.",
      "diagnostic_tags": [
        "titration_equivalence",
        "proportional"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-039",
      "skill": "phy-protocol",
      "secondary_skill": "rea-justify",
      "category": "B",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "في المتابعة الزمنية بالمعايرة، لماذا توضع عينات التفاعل في (ماء بارد + جليد) قبل المعايرة؟",
      "options": [
        {
          "id": "A",
          "text": "لتسريع التفاعل وبلوغ النهاية أسرع",
          "diagnostic_error": "عكس التأثير الحراري (البرد يبطئ لا يسرع)"
        },
        {
          "id": "B",
          "text": "لإيقاف التفاعل عند اللحظة المرادة (سقي فيزيائي)",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "لزيادة حجم التكافؤ V_E",
          "diagnostic_error": "الاعتقاد أن السقي يؤثر على المصير النهائي (وهو لا يؤثر)"
        },
        {
          "id": "D",
          "text": "لتغيير التركيب المولي النهائي",
          "diagnostic_error": "الخلط بين السقي والتركيز"
        }
      ],
      "correct": "B",
      "explanation": "التبريد المفاجئ (السقي) يوقف التفاعل دون تغيير كمية المادة؛ لا يؤثر على V_E ولا على التركيب النهائي.",
      "diagnostic_tags": [
        "quenching",
        "kinetic_factor_temperature"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-040",
      "skill": "phy-protocol",
      "secondary_skill": "phy-table",
      "category": "B",
      "difficulty": 3,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit3",
        "unit4"
      ],
      "question": "عند قياس الناقلية G = K·σ، فإن ثابت الخلية K له وحدة الطول (m) لأنه قسمة مساحة على مسافة (S/L). لماذا يُنتبه لتسجيل σ (الناقلية النوعية) وليس فقط G؟",
      "options": [
        {
          "id": "A",
          "text": "لأن G هي نفسها σ دائماً",
          "diagnostic_error": "الخلط بين G وσ (يصمح K)"
        },
        {
          "id": "B",
          "text": "لأن σ لا علاقة لها بالتركيز",
          "diagnostic_error": "إنكار العلاقة σ مع التراكيز"
        },
        {
          "id": "C",
          "text": "لأن قياس G مستحيل عملياً",
          "diagnostic_error": "خطأ واقعي: G تقاس بمقياس الناقلية"
        },
        {
          "id": "D",
          "text": "لأن σ مستقلة عن شكل الخلية وتسمح بالحساب من التركيز عبر σ = Σλi·[Xi]",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "σ مرتبطة مباشرة بتراكيز الشوارد عبر الناقليات المولية، بينما G تعتمد على خلية القياس (K).",
      "diagnostic_tags": [
        "conductivity",
        "cell_constant"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-041",
      "skill": "rea-method",
      "secondary_skill": null,
      "category": "C",
      "difficulty": 1,
      "estimated_time": 30,
      "prerequisite_lessons": [
        "unit1",
        "unit2",
        "unit3",
        "unit4",
        "unit5"
      ],
      "question": "ما الترتيب الصحيح لحل مسألة فيزيائية؟",
      "options": [
        {
          "id": "A",
          "text": "اختيار العلاقة أولاً ثم استخراج المعطيات",
          "diagnostic_error": "اعتماد العلاقة قبل الفهم"
        },
        {
          "id": "B",
          "text": "الحساب ثم المعطيات",
          "diagnostic_error": "عكس المنهجية المعتمدة"
        },
        {
          "id": "C",
          "text": "التعويض المباشر دون تحديد المطلوب",
          "diagnostic_error": "إجراء بلا توجيه"
        },
        {
          "id": "D",
          "text": "استخراج المعطيات ← تحديد المطلوب ← اختيار العلاقة ← التعويض ← التحقق",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "المنهجية الموثقة في كل الوحدات تبدأ بفهم المعطيات وتحديد المطلوب قبل اختيار العلاقة.",
      "diagnostic_tags": [
        "methodology_steps"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-042",
      "skill": "rea-method",
      "secondary_skill": null,
      "category": "C",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1",
        "unit2"
      ],
      "question": "في مسألة: \"يحتوي محلول على 5 g من صوديوم مذاب في 250 mL، احسب التركيز المولي مع العلم M = 23 g/mol\". ما المعطيات الزائدة أو المفتقدة للتعويض؟",
      "options": [
        {
          "id": "A",
          "text": "المعطيات ناقصة: نفتقد درجة الحرارة",
          "diagnostic_error": "درجة الحرارة غير لازمة هنا"
        },
        {
          "id": "B",
          "text": "المعطيات زائدة: M لا لزوم لها",
          "diagnostic_error": "M ضرورية لحساب n"
        },
        {
          "id": "C",
          "text": "المعطيات زائدة: V لا لزوم له",
          "diagnostic_error": "V ضرورية لتحويل n إلى C"
        },
        {
          "id": "D",
          "text": "اكتمل كل المطلوب: m، V، M لاستعمال n=m/M ثم C=n/V",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "المنهجية: المطلوب C؛ نستعمل m,M لنحسب n=m/M ثم نحول C=n/V (مع تحويل 250 mL إلى L).",
      "diagnostic_tags": [
        "data_filtering",
        "two_step_calculation"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-043",
      "skill": "rea-method",
      "secondary_skill": "mat-unitconv",
      "category": "C",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit1",
        "unit2",
        "unit5"
      ],
      "question": "قبل التعويض في علاقة، ما التحقق الأهم أولاً بعد التأكد من نوع الكمية؟",
      "options": [
        {
          "id": "A",
          "text": "إهمال الوحدات لأن القيم أرقام فقط",
          "diagnostic_error": "الوحدات جوهرية للتحقق"
        },
        {
          "id": "B",
          "text": "مضاعفة القيم لتسهيل الحساب",
          "diagnostic_error": "تغيير المعطيات يخل بالنتيجة"
        },
        {
          "id": "C",
          "text": "توحيد وحدات كل الكميات بالنظام الدولي (تحويل mL→L، g→kg...)",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "استعمال الوحدات غير الرسمية كما هي",
          "diagnostic_error": "يؤدي غالباً لنتيجة خاطئة"
        }
      ],
      "correct": "C",
      "explanation": "التحقق البعدي/الوحدي أولاً: التجانس مسبق للتعويض به يضمن نتيجة صحيحة الأبعاد.",
      "diagnostic_tags": [
        "unit_inspection",
        "pre_substitution"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-044",
      "skill": "rea-justify",
      "secondary_skill": "rea-compare",
      "category": "C",
      "difficulty": 2,
      "estimated_time": 60,
      "prerequisite_lessons": [
        "unit1"
      ],
      "question": "رفعنا درجة حرارة تفاعل بطيء. بعد التبريد عاد التفاعل بنفاد أسرع؟ ما التبرير الصحيح لتأثير الحرارة؟",
      "options": [
        {
          "id": "A",
          "text": "الحرارة ترفع تواتر التصادمات الفعالة فتزداد السرعة وينقص t₁/₂",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "الحرارة لا تأثير لها إطلاقاً",
          "diagnostic_error": "إنكار عامل حركي"
        },
        {
          "id": "C",
          "text": "الحرارة تغير طبيعة التفاعل (تام بدل محدود)",
          "diagnostic_error": "إذا كان تاماً يبقى تاماً"
        },
        {
          "id": "D",
          "text": "الحرارة تستهلك المتفاعلات فتزيد كمية النواتج",
          "diagnostic_error": "خلط العامل الحركي بالتركيب"
        }
      ],
      "correct": "A",
      "explanation": "الحرارة عامل حركي: ترفع سرعة التفاعل بدون تغيير التركيب المولي النهائي (مع بقاء t₁/₂ ينقص).",
      "diagnostic_tags": [
        "kinetic_factor",
        "temperature_effect"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-045",
      "skill": "rea-justify",
      "secondary_skill": "mat-num",
      "category": "C",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "تتحول نواة X إلى نواة Y بإصدار إلكترون e⁻ (تفكك β⁻) حسب: ^(A)Z(X) → ^(A)(Z+1)(Y) + e⁻. أي مبدأ تحققوه هنا؟",
      "options": [
        {
          "id": "A",
          "text": "لا انحفاظ يتطلب في التفاعلات النووية",
          "diagnostic_error": "مبدأان دائماً محفوظان"
        },
        {
          "id": "B",
          "text": "انحفاظ العدد الذري فقط",
          "diagnostic_error": "نسيان انحفاظ A"
        },
        {
          "id": "C",
          "text": "انحفاظ عدد النترونات N = A − Z",
          "diagnostic_error": "انحفاظ A وZ لا يفرض انحفاظ N (N انعكس)"
        },
        {
          "id": "D",
          "text": "انحفاظ العدد الكتلي A وانحفاظ العدد الذري Z",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "في كل التفاعلات النووية يتحقق انحفاظ العدد الكتلي والعدد الذري (فحص A: A=A+0، Z: Z=Z+1−1).",
      "diagnostic_tags": [
        "conservation_laws",
        "beta_decay"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-046",
      "skill": "rea-justify",
      "secondary_skill": "phy-graph",
      "category": "C",
      "difficulty": 4,
      "estimated_time": 90,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "منحنى v(t) لجسم هو خط مستقيم متناقص يلتقي المحور الأفقي عند t = 6 s ثم يبقى عند v=0. أي استنتاج صحيح؟",
      "options": [
        {
          "id": "A",
          "text": "حركة مستقيمة متباطئة حتى السكون ثم يستقر",
          "diagnostic_error": null
        },
        {
          "id": "B",
          "text": "حركة منتظمة",
          "diagnostic_error": "الخط ليس أفقياً وسطياً"
        },
        {
          "id": "C",
          "text": "الجسم يرتد ويغير اتجاهه",
          "diagnostic_error": "لا دليل على انعكاس الاتجاه (v تبقى ≥0)"
        },
        {
          "id": "D",
          "text": "حركة متسارعة بانتظام",
          "diagnostic_error": "الميل سالب ثابت = تباطؤ لا تسارع"
        }
      ],
      "correct": "A",
      "explanation": "ميل سالب ثابت ⇒ تباطؤ منتظم حتى v=0 عند t=6 ثم بقاء (سكون). (a·v < 0 حتى الصفر).",
      "diagnostic_tags": [
        "decreasing_slope",
        "motion_type_inference"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-047",
      "skill": "rea-compare",
      "secondary_skill": "mat-logexp",
      "category": "C",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit4"
      ],
      "question": "حمضان ضعيفان لهما نفس التركيز: حمض A ثابت Ka = 10⁻⁴ وحمض B ثابت Ka = 10⁻⁶. أي منهما الحمض الأقوى؟",
      "options": [
        {
          "id": "A",
          "text": "B هو الأقوى",
          "diagnostic_error": "عكس منطق المقارنة عبر Ka"
        },
        {
          "id": "B",
          "text": "A هو الأقوى (Ka أكبر ⇒ تفكك أكبر ⇒ τf أكبر و pH أصغر)",
          "diagnostic_error": null
        },
        {
          "id": "C",
          "text": "متعادلان تماماً",
          "diagnostic_error": "Ka مختلفان فهما لا يتعادلان"
        },
        {
          "id": "D",
          "text": "لا يمكن الجواب بدون قياس pH",
          "diagnostic_error": "Ka يعطي الجواب مباشرة للمقارنة"
        }
      ],
      "correct": "B",
      "explanation": "كلما كبر Ka قوي الحمض: A (Ka=10⁻⁴ أكبر) فالأقوى (وبالتالي τf أكبر وpH أصغر).",
      "diagnostic_tags": [
        "acid_strength_compare",
        "ka_order"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-048",
      "skill": "rea-compare",
      "secondary_skill": "rea-justify",
      "category": "C",
      "difficulty": 5,
      "estimated_time": 120,
      "prerequisite_lessons": [
        "unit2"
      ],
      "question": "قارن القيم التالية لنواتين: نواة 1 ومقابلها 2. أي استنتاج منطقي (استقرار أكبر = طاقة ربط لكل نوية أكبر)؟",
      "options": [
        {
          "id": "A",
          "text": "الاستقرار يتساوى لكل النوى",
          "diagnostic_error": "El/A يتغير عبر مخطط النوى"
        },
        {
          "id": "B",
          "text": "الاستقرار يزداد كلما زادت الكتلة دائمًا",
          "diagnostic_error": "الكتلة وحدها لا تحدد الاستقرار"
        },
        {
          "id": "C",
          "text": "استقرار النواة يزداد كلما زادت El/A (طاقة الربط لكل نوية)",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "الاستقرار يزداد كلما نقص Z",
          "diagnostic_error": "نقصان Z ليس لحظاً للاستقرار في كل الحالات"
        }
      ],
      "correct": "C",
      "explanation": "الاستقرار النووي يُقارن بطاقة الربط لكل نوية El/A؛ كلما كانت أكبر كانت النواة أكثر استقراراً.",
      "diagnostic_tags": [
        "nuclear_stability",
        "binding_per_nucleon"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-049",
      "skill": "rea-modelize",
      "secondary_skill": "mat-logexp",
      "category": "C",
      "difficulty": 3,
      "estimated_time": 75,
      "prerequisite_lessons": [
        "unit3"
      ],
      "question": "لدينا شحن مكثفة: العلاقة العامة uC(t) = E(1 − e^(−t/(RC))). ما النمذجة الصحيحة لتطور شدة التيار i(t) علماً أن i = C·duC/dt؟",
      "options": [
        {
          "id": "A",
          "text": "i(t) = E/R ثابتة طوال الوقت",
          "diagnostic_error": "الاعتقاد i ثابتة (نسيان أن الشحن يتوقف)"
        },
        {
          "id": "B",
          "text": "i(t) = (E/R)·(1 − e^(−t/(RC)))",
          "diagnostic_error": "اعتبار i تصعد لنفس نموذج uC (خطأ منطقي)"
        },
        {
          "id": "C",
          "text": "i(t) = (E/R)·e^(−t/(RC)) (قاس من اشتقاق uC)",
          "diagnostic_error": null
        },
        {
          "id": "D",
          "text": "i(t) = C·E·t",
          "diagnostic_error": "خطأ خطي بدل أسيّ (اشتقاق خاطئ)"
        }
      ],
      "correct": "C",
      "explanation": "باشتقاق uC: duC/dt = E/(RC)·e^(−t/RC)، وبعد الضرب في C: i = (E/R)·e^(−t/RC) (تناقص أسي).",
      "diagnostic_tags": [
        "modelize_current",
        "derive_charging"
      ],
      "weight": 1
    },
    {
      "id": "PHYV2-050",
      "skill": "rea-modelize",
      "secondary_skill": "mat-calc",
      "category": "C",
      "difficulty": 5,
      "estimated_time": 120,
      "prerequisite_lessons": [
        "unit5"
      ],
      "question": "جسم في سقوط حر مع إهمال مقاومة الهواء: الشرط أن التسارع ثابت (a = g). اختر النموذج الرياضي الصحيح لطبيعة الحركة (بدون سرعة ابتدائية).",
      "options": [
        {
          "id": "A",
          "text": "v(t) = g·t و z(t) = g·t²",
          "diagnostic_error": "نسيان المعامل 1/2 في التكامل الثاني"
        },
        {
          "id": "B",
          "text": "v(t) = v₀ + at و z(t) = v₀t + at²",
          "diagnostic_error": "نموذج هجين صحيح جزئياً لكن بلا 1/2 على at² (تسارع ثابت لكن المعامل خاطئ)"
        },
        {
          "id": "C",
          "text": "v(t) = ثابت و z(t) = v·t",
          "diagnostic_error": "نموذج الحركة المنتظمة (خطأ: a=0)"
        },
        {
          "id": "D",
          "text": "v(t) = g·t و z(t) = (1/2)g·t²",
          "diagnostic_error": null
        }
      ],
      "correct": "D",
      "explanation": "بتكامل a = g: v = g·t + v₀ (مع v₀ = 0)، ثم بتكامل v: z = (1/2)g·t² + z₀. النموذج الصحيح فيه المعامل 1/2.",
      "diagnostic_tags": [
        "model_free_fall",
        "double_integration"
      ],
      "weight": 1
    }
  ]
}
