-- ============================================================
-- Migration 006: Seed diagnostic question bank (physics bac)
-- Generated by scripts/build-diagnostic-seed.js — DO NOT EDIT.
-- Source of truth: scripts/question-bank.js
-- ============================================================

insert into public.diagnostic_tests (id, title, description, subject, grade, version, question_bank_version, total_questions, time_limit_minutes, is_active)
values (
  'bac-physics-v1',
  'اختبار تحديد المستوى في الفيزياء',
  'اختبار تشخيصي من 40 سؤالاً لطلاب البكالوريا في الفيزياء. يقيس المهارات الأساسية: الرياضيات، الوحدات والرموز، المفاهيم الفيزيائية، قراءة البيانات، حل المسائل، والمنهجية.',
  'physics',
  'baccalaureate',
  1,
  '2024-09-v1',
  40,
  60,
  true
)
on conflict (id) do update set title = excluded.title, description = excluded.description, version = excluded.version, question_bank_version = excluded.question_bank_version, total_questions = excluded.total_questions, time_limit_minutes = excluded.time_limit_minutes, is_active = excluded.is_active;

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-001',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  null,
  'scientific_notation',
  1,
  'أكتب العدد 0.00052 بالكتابة العلمية.',
  '[{"id":"A","text":"5.2 × 10⁻⁴","diagnostic_tag":null},{"id":"B","text":"5.2 × 10⁴","diagnostic_tag":"decimal_direction_error"},{"id":"C","text":"52 × 10⁻⁵","diagnostic_tag":"not_scientific_form"},{"id":"D","text":"0.52 × 10⁻³","diagnostic_tag":"not_scientific_form"}]'::jsonb,
  'A',
  'لتحويل 0.00052 إلى كتابة علمية نحرك الفاصلة 4 خانات نحو اليمين فينتج الأس ‎-4: 5.2 × 10⁻⁴.',
  '["scientific_notation","power_of_ten","decimal_point_movement"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-007',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  null,
  'powers_of_ten',
  2,
  'احسب:  (2 × 10³) × (3 × 10⁻²)',
  '[{"id":"A","text":"60","diagnostic_tag":null},{"id":"B","text":"0.6","diagnostic_tag":"exponent_multiplication_error"},{"id":"C","text":"6","diagnostic_tag":"forgotten_ten_factor"},{"id":"D","text":"600","diagnostic_tag":"exponent_sign_error"}]'::jsonb,
  'A',
  'نضرب الأعداد (2×3=6) ونجمع الأسس: 10^(3-2)=10¹، فينتج 6 × 10¹ = 60.',
  '["powers_of_ten","exponent_addition","multiplication"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-013',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  null,
  'rearranging_formula',
  2,
  'من العلاقة  F = m × a  ، أعزل التسارع a:',
  '[{"id":"A","text":"a = F / m","diagnostic_tag":null},{"id":"B","text":"a = F × m","diagnostic_tag":"moved_side_as_multiplication"},{"id":"C","text":"a = m / F","diagnostic_tag":"inverted_fraction"},{"id":"D","text":"a = F − m","diagnostic_tag":"subtraction_misconception"}]'::jsonb,
  'A',
  'لإيجاد a نقسم طرفي المعادلة على m: a = F/m.',
  '["rearrange_formula","isolate_variable","algebra"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-018',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  'problem_solving',
  'square_root_and_estimate',
  2,
  'في العلاقة الدورية لنواس بسيط  T = 2π√(L/g) ، إذا كان L = 1 m  و g = 10 m/s² ، فما القيمة التقريبية لـ T (باستعمال 2π ≈ 6.3)؟',
  '[{"id":"A","text":"≈ 2.0 s","diagnostic_tag":null},{"id":"B","text":"≈ 0.63 s","diagnostic_tag":"forgot_square_root"},{"id":"C","text":"≈ 6.3 s","diagnostic_tag":"root_of_whole_ratio_error"},{"id":"D","text":"≈ 1.26 s","diagnostic_tag":"root_of_numerator_only"}]'::jsonb,
  'A',
  '√(1/10) = √0.1 ≈ 0.316 وبالتالي T ≈ 6.3 × 0.316 ≈ 2.0 s.',
  '["square_root","estimate","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-023',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  'concepts',
  'proportionality',
  2,
  'في موصل أومي مقاومته R ثابتة، إذا تضاعف التيار المار فيه، فإن التوتر بين طرفيه:',
  '[{"id":"A","text":"يتضاعف","diagnostic_tag":null},{"id":"B","text":"ينقص إلى النصف","diagnostic_tag":"inverse_relation_error"},{"id":"C","text":"يبقى ثابتاً","diagnostic_tag":"linearity_unknown"},{"id":"D","text":"يصبح معدومًا","diagnostic_tag":"voltage_elimination_error"}]'::jsonb,
  'A',
  'من قانون أوم U = R × I، مع R ثابتة فإن U تتناسب طردًا مع I: إذا تضاعف التيار تضاعف التوتر.',
  '["proportionality","direct_relation","ohm_law"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-028',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  null,
  'scientific_notation_division',
  3,
  'احسب:   (8 × 10⁶) ÷ (4 × 10⁻²)',
  '[{"id":"A","text":"2 × 10⁸","diagnostic_tag":null},{"id":"B","text":"2 × 10⁴","diagnostic_tag":"exponents_added_not_subtracted"},{"id":"C","text":"2 × 10³","diagnostic_tag":"division_of_exponents"},{"id":"D","text":"2 × 10⁻⁸","diagnostic_tag":"sign_error_in_exponents"}]'::jsonb,
  'A',
  '8 ÷ 4 = 2 وللقسمة نطرح الأسس: 10^(6-(-2)) = 10⁸، أي 2 × 10⁸.',
  '["division","exponent_subtraction","scientific_notation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-033',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  'concepts',
  'percentage_calculation',
  1,
  'في تحول كيميائي، تحول %25 من الكمية الابتدائية البالغة 80 mol لمادة ما. كم مول تحول فعليًا؟',
  '[{"id":"A","text":"20 mol","diagnostic_tag":null},{"id":"B","text":"25 mol","diagnostic_tag":"percentage_number_confusion"},{"id":"C","text":"55 mol","diagnostic_tag":"remaining_amount_error"},{"id":"D","text":"200 mol","diagnostic_tag":"multiplication_by_percent_error"}]'::jsonb,
  'A',
  '25% من 80 = (25/100) × 80 = 20 mol.',
  '["percentage","proportion","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-039',
  'bac-physics-v1',
  'single_choice',
  'math',
  'math',
  null,
  'solving_equation',
  3,
  'حل المعادلة  2t² − 8 = 0  علماً أن t > 0:',
  '[{"id":"A","text":"t = 2","diagnostic_tag":null},{"id":"B","text":"t = 4","diagnostic_tag":"missing_square_root"},{"id":"C","text":"t = 16","diagnostic_tag":"squared_value_kept"},{"id":"D","text":"t = ±2","diagnostic_tag":"negative_root_ignored_condition"}]'::jsonb,
  'A',
  '2t² = 8 إذن t² = 4 وبما أن t>0 فإن t = +2.',
  '["quadratic","solve_equation","positive_root"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-002',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  null,
  'speed_conversion',
  1,
  'جسم يتحرك بسرعة 72 km/h. ما سرعته بوحدة m/s؟',
  '[{"id":"A","text":"20 m/s","diagnostic_tag":null},{"id":"B","text":"259.2 m/s","diagnostic_tag":"conversion_multiplication_error"},{"id":"C","text":"10 m/s","diagnostic_tag":"halved_value_error"},{"id":"D","text":"72 m/s","diagnostic_tag":"unit_not_converted"}]'::jsonb,
  'A',
  'لتحويل km/h إلى m/s نقسم على 3.6: 72 ÷ 3.6 = 20 m/s.',
  '["speed_conversion","division_by_3_6","unit_not_converted"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-008',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  'math',
  'prefix_conversion',
  1,
  'ما قيمة 2500 μm بوحدة mm؟',
  '[{"id":"A","text":"2.5 mm","diagnostic_tag":null},{"id":"B","text":"25 mm","diagnostic_tag":"factor_ten_error"},{"id":"C","text":"0.25 mm","diagnostic_tag":"factor_ten_opposite"},{"id":"D","text":"250 mm","diagnostic_tag":"prefix_ignored"}]'::jsonb,
  'A',
  '1 μm = 10⁻⁶ m و 1 mm = 10⁻³ m، فالعلاقة 1 mm = 1000 μm، إذن 2500 μm = 2.5 mm.',
  '["prefix_conversion","micro_to_milli","powers_of_ten"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-014',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  null,
  'volume_conversion',
  2,
  'ما قيمة 250 cm³ بوحدة اللتر (L)؟',
  '[{"id":"A","text":"0.25 L","diagnostic_tag":null},{"id":"B","text":"2.5 L","diagnostic_tag":"factor_ten_error"},{"id":"C","text":"25 L","diagnostic_tag":"factor_hundred_error"},{"id":"D","text":"0.025 L","diagnostic_tag":"opposite_factor_error"}]'::jsonb,
  'A',
  '1 L = 1 dm³ = 1000 cm³، إذن 250 cm³ = 0.25 L.',
  '["volume_conversion","liter","cubic_centimeter"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-019',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  'concepts',
  'si_activity_unit',
  2,
  'ما وحدة قياس النشاط الإشعاعي في النظام الدولي SI؟',
  '[{"id":"A","text":"البيكريل (Bq)","diagnostic_tag":null},{"id":"B","text":"الجول (J)","diagnostic_tag":"energy_unit_confusion"},{"id":"C","text":"الواط (W)","diagnostic_tag":"power_unit_confusion"},{"id":"D","text":"الهيرتز (Hz)","diagnostic_tag":"frequency_unit_confusion"}]'::jsonb,
  'A',
  'النشاط الإشعاعي هو عدد التفككات في الثانية ويقاس بالبيكريل Bq.',
  '["si_units","activity","becquerel"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-021',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  'concepts',
  'rate_constant_unit',
  3,
  'في تفاعل من الرتبة 1، تُعطى سرعة التفاعل بالعلاقة  v = k × [A] . ما وحدة ثابتة السرعة k في النظام الدولي؟',
  '[{"id":"A","text":"s⁻¹","diagnostic_tag":null},{"id":"B","text":"mol·L⁻¹·s⁻¹","diagnostic_tag":"unit_of_velocity_mistaken"},{"id":"C","text":"L·mol⁻¹·s⁻¹","diagnostic_tag":"second_order_constant"},{"id":"D","text":"mol·L⁻¹","diagnostic_tag":"concentration_unit_mistaken"}]'::jsonb,
  'A',
  'v بوحدة mol·L⁻¹·s⁻¹ و[A] بوحدة mol·L⁻¹، إذن k = v/[A] وهو بوحدة s⁻¹.',
  '["rate_constant_unit","reaction_order","dimensional_analysis"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-029',
  'bac-physics-v1',
  'single_choice',
  'units',
  'units',
  'math',
  'dimensions',
  3,
  'ما وحدة المقاومة الكهربائية (الأوم Ω) بدلالة وحدات النظام الدولي الأساسية؟',
  '[{"id":"A","text":"kg·m²·s⁻³·A⁻²","diagnostic_tag":null},{"id":"B","text":"kg·m²·s⁻²·A⁻¹","diagnostic_tag":"energy_unit_confusion"},{"id":"C","text":"kg·m·s⁻²","diagnostic_tag":"newton_unit_confusion"},{"id":"D","text":"kg·m·s⁻¹","diagnostic_tag":"momentum_unit_confusion"}]'::jsonb,
  'A',
  'R = U/I، حيث U = J/C …، وبالحساب البعدي يكون الأوم = kg·m²·s⁻³·A⁻².',
  '["dimensions","si_base_units","resistance"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-003',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'speed_vs_velocity',
  1,
  'أي عبارة صحيحة حول السرعة المتوسطة؟',
  '[{"id":"A","text":"هي المسافة المقطوعة مقسومة على مدة القطع","diagnostic_tag":null},{"id":"B","text":"هي تغير الموضع مقسومًا على المدة","diagnostic_tag":"vector_velocity_misconception"},{"id":"C","text":"تساوي دائمًا السرعة اللحظية","diagnostic_tag":"average_vs_instantaneous"},{"id":"D","text":"لا تعتمد على المسار المقطوع","diagnostic_tag":"path_dependence_error"}]'::jsonb,
  'A',
  'السرعة المتوسطة كمية قياسية: المسافة ÷ المدة. أما تغير الموضع ÷ المدة فهو السرعة المتجهة المتوسطة.',
  '["average_speed","scalar_vs_vector","path_dependence"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-009',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'newton_first_law',
  2,
  'جسم يتحرك بسرعة ثابتة في خط مستقيم. أي استنتاج صحيح؟',
  '[{"id":"A","text":"محصلة القوى المطبقة عليه معدومة","diagnostic_tag":null},{"id":"B","text":"توجد بالضرورة قوة في اتجاه الحركة","diagnostic_tag":"motion_requires_force"},{"id":"C","text":"لا توجد أي قوة مطبقة على الجسم","diagnostic_tag":"no_forces_at_all"},{"id":"D","text":"محصلة القوى تتناسب مع السرعة","diagnostic_tag":"force_proportional_to_velocity"}]'::jsonb,
  'A',
  'قانون نيوتن الأول: الحركة المستقيمة المنتظمة تعني انعدام محصلة القوى، وليس انعدام القوى كلها.',
  '["newton_first_law","resultant_force","uniform_motion"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-015',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  'units',
  'mass_vs_weight',
  2,
  'رائد فضاء يعمل على سطح القمر حيث الجاذبية تساوي سدس جاذبية الأرض. أي كمية تتغير نتيجة ذلك؟',
  '[{"id":"A","text":"وزنه فقط","diagnostic_tag":null},{"id":"B","text":"كتلته فقط","diagnostic_tag":"mass_changes_misconception"},{"id":"C","text":"وزنه وكتلته معًا","diagnostic_tag":"both_change_misconception"},{"id":"D","text":"لا تتغير أي كمية","diagnostic_tag":"nothing_changes_misconception"}]'::jsonb,
  'A',
  'الكتلة كمية مستقلة عن الجاذبية، أما الوزن P = m×g فيتغير بتغير g.',
  '["mass_vs_weight","gravity_dependence","weight_formula"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-020',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'action_reaction',
  2,
  'عندما يدفع شخص حائطًا بقوة، يندفع الشخص إلى الخلف. أي قانون يفسر هذه الظاهرة؟',
  '[{"id":"A","text":"قانون الفعل ورد الفعل (نيوتن الثالث)","diagnostic_tag":null},{"id":"B","text":"قانون القصور الذاتي","diagnostic_tag":"first_law_misapplied"},{"id":"C","text":"قانون نيوتن الثاني","diagnostic_tag":"second_law_misapplied"},{"id":"D","text":"قانون حفظ الكمية الحركة","diagnostic_tag":"momentum_law_misapplied"}]'::jsonb,
  'A',
  'الحائط يطبق على الشخص قوة رد فعل مساوية في المقدار ومعاكسة في الاتجاه (نيوتن الثالث).',
  '["newton_third_law","action_reaction","force_pairs"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-024',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'equilibrium_constant_meaning',
  3,
  'عند درجة حرارة ثابتة، ثابت التوازن K لجملة كيميائية في حالة التوازن:',
  '[{"id":"A","text":"لا يعتمد على التركيزات الابتدائية","diagnostic_tag":null},{"id":"B","text":"يتغير عند إضافة كمية من متفاعل","diagnostic_tag":"conc_change_misconception"},{"id":"C","text":"يتغير عند إزالة ناتج من الوسط","diagnostic_tag":"product_removal_misconception"},{"id":"D","text":"يتغير عند تغيير الحجم","diagnostic_tag":"volume_change_misconception"}]'::jsonb,
  'A',
  'ثابت التوازن يعتمد على درجة الحرارة فقط، ويبقى ثابتًا عند تغيير التركيزات أو الحجم عند نفس الحرارة.',
  '["equilibrium_constant","temperature_dependence","le_chatelier_basics"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-030',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  'math',
  'current_voltage_relation',
  2,
  'في دارة تتكون من مولّد وناقل أومي، إذا زاد التوتر المطبق بين طرفي الناقل دون تغيير مقاومته، فإن شدة التيار:',
  '[{"id":"A","text":"تزداد بنفس النسبة تقريبًا","diagnostic_tag":null},{"id":"B","text":"تتناقص","diagnostic_tag":"inverse_relation_error"},{"id":"C","text":"لا تتغير","diagnostic_tag":"resistance_only_perception"},{"id":"D","text":"تنعدم","diagnostic_tag":"current_elimination_error"}]'::jsonb,
  'A',
  'من قانون أوم I = U/R: عند ثبات R يزداد التيار طردًا مع التوتر.',
  '["ohm_law","current_voltage_relation","direct_proportionality"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-034',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'relative_motion',
  3,
  'راكب يجلس بثبات داخل قطار يتحرك بسرعة ثابتة في خط مستقيم. بالنسبة لراكب آخر يجلس في نفس القطار، فإن الراكب الأول:',
  '[{"id":"A","text":"ساكن (حركته معدومة)","diagnostic_tag":null},{"id":"B","text":"يتحرك بنفس سرعة القطار","diagnostic_tag":"reference_frame_error"},{"id":"C","text":"يتحرك بسرعة مضاعفة","diagnostic_tag":"double_speed_error"},{"id":"D","text":"يتحرك بعكس اتجاه القطار","diagnostic_tag":"opposite_direction_error"}]'::jsonb,
  'A',
  'الحركة نسبية: الراكبان في نفس المعلم (القطار)، فالراكب الأول ساكن بالنسبة للثاني.',
  '["relative_motion","frame_of_reference","repos_perception"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-037',
  'bac-physics-v1',
  'single_choice',
  'concepts',
  'concepts',
  null,
  'energy_transformation',
  2,
  'عند سقوط حجر من ارتفاع معين (مع إهمال مقاومة الهواء)، تتحول طاقته الكامنة الثقالية إلى:',
  '[{"id":"A","text":"طاقة حركية","diagnostic_tag":null},{"id":"B","text":"طاقة كيميائية","diagnostic_tag":"chemical_energy_error"},{"id":"C","text":"طاقة نووية","diagnostic_tag":"nuclear_energy_error"},{"id":"D","text":"تبقى كامنة دون تغيير","diagnostic_tag":"no_transformation_error"}]'::jsonb,
  'A',
  'أثناء السقوط تنخفض الطاقة الكامنة وتزداد الطاقة الحركية بنفس المقدار (حفظ الطاقة الميكانيكية).',
  '["energy_transformation","potential_to_kinetic","energy_conservation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-004',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'concepts',
  'table_reading',
  1,
  'جدول يعطي موضع جسم في لحظات مختلفة: (0;0) ، (1;2) ، (2;4) ، (3;6) حيث الزمن بالثانية والموضع بالمتر. طبيعة هذه الحركة:',
  '[{"id":"A","text":"حركة مستقيمة منتظمة","diagnostic_tag":null},{"id":"B","text":"حركة مستقيمة متسارعة بانتظام","diagnostic_tag":"acceleration_misread"},{"id":"C","text":"حركة مستقيمة متباطئة","diagnostic_tag":"deceleration_misread"},{"id":"D","text":"الحركة مستحيلة من هذه البيانات","diagnostic_tag":"insufficient_data_error"}]'::jsonb,
  'A',
  'الإزاحة تزداد بمقدار ثابت (2 m) كل ثانية، أي السرعة ثابتة: الحركة منتظمة.',
  '["table_reading","uniform_motion","constant_displacement"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-010',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'problem_solving',
  'slope_reading',
  2,
  'منحنى v(t) لحركة جسم هو خط مستقيم يمر بالنقطتين (2; 6) و (6; 18) (الزمن بالثانية والسرعة بـ m/s). ما قيمة التسارع؟',
  '[{"id":"A","text":"3 m/s²","diagnostic_tag":null},{"id":"B","text":"2 m/s²","diagnostic_tag":"division_error"},{"id":"C","text":"12 m/s²","diagnostic_tag":"denominator_omitted"},{"id":"D","text":"4 m/s²","diagnostic_tag":"interval_sum_error"}]'::jsonb,
  'A',
  'التسارع = ميل المستقيم = (18-6)/(6-2) = 12/4 = 3 m/s².',
  '["slope_reading","graph_interpretation","acceleration"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-016',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'concepts',
  'x_t_slope_meaning',
  2,
  'من منحنى الموضع x(t) لحركة مستقيمة، ميل المماس للمنحنى عند لحظة معينة يمثل:',
  '[{"id":"A","text":"السرعة اللحظية","diagnostic_tag":null},{"id":"B","text":"التسارع اللحظي","diagnostic_tag":"slope_meaning_confusion"},{"id":"C","text":"المسافة الكلية المقطوعة","diagnostic_tag":"position_misread"},{"id":"D","text":"الزمن المستغرق","diagnostic_tag":"time_misread"}]'::jsonb,
  'A',
  'مشتقة الموضع بالنسبة للزمن dx/dt هي السرعة اللحظية، وهي ميل المماس لمنحنى x(t).',
  '["x_t_graph","tangent_slope","instantaneous_velocity"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-025',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'math',
  'extrapolation',
  3,
  'في تجربة تبريد، سجلت النقاط (0; 80) و (5; 60) لدرجة الحرارة (بالدرجة) مقابل الزمن (بالدقيقة)، والتناقص خطي تقريبًا. ما درجة الحرارة المتوقعة عند t = 10 min؟',
  '[{"id":"A","text":"40 درجة","diagnostic_tag":null},{"id":"B","text":"20 درجة","diagnostic_tag":"extrapolation_miscomputed"},{"id":"C","text":"30 درجة","diagnostic_tag":"half_rate_error"},{"id":"D","text":"50 درجة","diagnostic_tag":"rate_confusion"}]'::jsonb,
  'A',
  'الميل = (60-80)/5 = -4 درجة/دقيقة، عند t=10: 80 - 4×10 = 40 درجة.',
  '["extrapolation","linear_model","table_reading"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-031',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'concepts',
  'graph_shape_interpretation',
  3,
  'منحنى السرعة v(t) لحركة جسم هو خط مستقيم صاعد يمر بمبدأ المحورين. أي عبارة صحيحة؟',
  '[{"id":"A","text":"الحركة مستقيمة متسارعة بانتظام","diagnostic_tag":null},{"id":"B","text":"الحركة مستقيمة منتظمة","diagnostic_tag":"constant_slope_confusion"},{"id":"C","text":"الجسم ساكن","diagnostic_tag":"zero_motion_misread"},{"id":"D","text":"الحركة متباطئة","diagnostic_tag":"direction_of_slope_misread"}]'::jsonb,
  'A',
  'خط مستقيم صاعد يمر بالمبدأ يعني أن الميل (التسارع) ثابت موجب: حركة متسارعة بانتظام.',
  '["graph_shape","uniform_acceleration","v_t_graph"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-035',
  'bac-physics-v1',
  'single_choice',
  'data',
  'data',
  'problem_solving',
  'oscilloscope_reading',
  4,
  'على شاشة راسم الاهتزاز الكهربائي، القيمة الحساسة الأفقية هي 10 ms/تقسيمة، وتشغل دورة كاملة أفقياً 4 تقسيمات. ما قيمة الدورة T؟',
  '[{"id":"A","text":"40 ms","diagnostic_tag":null},{"id":"B","text":"10 ms","diagnostic_tag":"single_division_reading"},{"id":"C","text":"4 s","diagnostic_tag":"unit_not_converted"},{"id":"D","text":"2.5 ms","diagnostic_tag":"division_instead_of_multiplication"}]'::jsonb,
  'A',
  'T = عدد التقسيمات × القيمة الحساسة = 4 × 10 = 40 ms.',
  '["oscilloscope_reading","period_reading","scale_multiplication"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-005',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'math',
  'simple_acceleration',
  2,
  'سيارة انطلقت من السكون وبلغت سرعة 30 m/s بعد مدة قدرها 10 s. ما تسارعها المتوسط؟',
  '[{"id":"A","text":"3 m/s²","diagnostic_tag":null},{"id":"B","text":"0.33 m/s²","diagnostic_tag":"inverted_fraction"},{"id":"C","text":"300 m/s²","diagnostic_tag":"multiplication_instead_of_division"},{"id":"D","text":"20 m/s²","diagnostic_tag":"wrong_delta_value"}]'::jsonb,
  'A',
  'a = (v − v₀) / t = (30 − 0) / 10 = 3 m/s².',
  '["extract_data","select_formula","acceleration","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-011',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'math',
  'free_fall_duration',
  2,
  'جسم سقط سقوطًا حرًا من ارتفاع h = 20 m بدون سرعة ابتدائية (خذ g = 10 m/s²). ما مدة السقوط؟',
  '[{"id":"A","text":"2 s","diagnostic_tag":null},{"id":"B","text":"4 s","diagnostic_tag":"forgot_square_root"},{"id":"C","text":"40 s","diagnostic_tag":"multiplication_instead_of_division"},{"id":"D","text":"1 s","diagnostic_tag":"half_time_error"}]'::jsonb,
  'A',
  'من h = ½ g t²: t² = 2h/g = 4، إذن t = 2 s.',
  '["free_fall","select_formula","solve_equation","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-017',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'math',
  'kinetic_energy',
  3,
  'جسم كتلته m = 2 kg يتحرك بسرعة v = 3 m/s. ما طاقته الحركية؟',
  '[{"id":"A","text":"9 J","diagnostic_tag":null},{"id":"B","text":"18 J","diagnostic_tag":"forgot_half"},{"id":"C","text":"6 J","diagnostic_tag":"mv_formula_used"},{"id":"D","text":"36 J","diagnostic_tag":"mv2_without_half"}]'::jsonb,
  'A',
  'Ec = ½ m v² = ½ × 2 × 9 = 9 J.',
  '["kinetic_energy","select_formula","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-022',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'units',
  'electric_power',
  2,
  'مصباح يعمل تحت توتر U = 12 V ويمر فيه تيار شدته I = 0.5 A. ما قدرته الكهربائية؟',
  '[{"id":"A","text":"6 W","diagnostic_tag":null},{"id":"B","text":"24 W","diagnostic_tag":"division_instead_of_multiplication"},{"id":"C","text":"12 W","diagnostic_tag":"current_ignored"},{"id":"D","text":"0.5 W","diagnostic_tag":"voltage_ignored"}]'::jsonb,
  'A',
  'P = U × I = 12 × 0.5 = 6 W.',
  '["electric_power","select_formula","calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-026',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'units',
  'half_life',
  3,
  'عينة مشعة نشاطها الابتدائي A₀ = 1600 Bq ونصف عمرها = يومان. ما نشاطها بعد مرور 6 أيام؟',
  '[{"id":"A","text":"200 Bq","diagnostic_tag":null},{"id":"B","text":"800 Bq","diagnostic_tag":"one_half_life_only"},{"id":"C","text":"400 Bq","diagnostic_tag":"two_half_lives_only"},{"id":"D","text":"267 Bq","diagnostic_tag":"direct_division"}]'::jsonb,
  'A',
  '6 أيام = 3 أنصاف عمر: A = 1600 × (1/2)³ = 200 Bq.',
  '["half_life","radioactive_decay","repeated_halving"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-032',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'math',
  'equilibrium_quotient',
  3,
  'تفاعل التوازن: 2A ⇌ B. عند التوازن [A] = 0.2 mol/L و [B] = 0.8 mol/L. احسب ثابت التوازن Kc = [B]/[A]².',
  '[{"id":"A","text":"20","diagnostic_tag":null},{"id":"B","text":"4","diagnostic_tag":"exponent_not_applied"},{"id":"C","text":"0.05","diagnostic_tag":"inverted_ratio"},{"id":"D","text":"2","diagnostic_tag":"concentration_sum"}]'::jsonb,
  'A',
  'Kc = 0.8 / (0.2)² = 0.8 / 0.04 = 20.',
  '["equilibrium_constant","concentration_substitution","exponent_processing"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-036',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'units',
  'newton_second_law',
  3,
  'جسم كتلته m = 500 g يكتسب تسارعًا a = 2 m/s². ما شدة القوة المؤثرة عليه بوحدة N؟',
  '[{"id":"A","text":"1 N","diagnostic_tag":null},{"id":"B","text":"1000 N","diagnostic_tag":"gram_not_converted"},{"id":"C","text":"100 N","diagnostic_tag":"unit_conversion_factor_error"},{"id":"D","text":"0.002 N","diagnostic_tag":"opposite_conversion"}]'::jsonb,
  'A',
  'نحول أولاً 500 g = 0.5 kg، ثم F = m × a = 0.5 × 2 = 1 N.',
  '["mass_conversion","newton_second_law","unit_conversion"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-040',
  'bac-physics-v1',
  'single_choice',
  'problem_solving',
  'problem_solving',
  'math',
  'multi_step_kinematics',
  4,
  'سيارة كتلتها 1000 kg تنطلق من السكون بتسارع ثابت a = 2 m/s² لمدة 5 s. ما المسافة التي تقطعها خلال هذه المدة؟',
  '[{"id":"A","text":"25 m","diagnostic_tag":null},{"id":"B","text":"50 m","diagnostic_tag":"forgot_half_fraction"},{"id":"C","text":"10 m","diagnostic_tag":"at_used_without_squaring"},{"id":"D","text":"100 m","diagnostic_tag":"mass_mixed_into_distance"}]'::jsonb,
  'A',
  'd = ½ a t² = ½ × 2 × 25 = 25 m (الكتلة لا تدخل في حساب المسافة هذه).',
  '["multi_step","kinematics","choose_and_combine_formulas","irrelevant_data_filter"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-006',
  'bac-physics-v1',
  'single_choice',
  'methodology',
  'methodology',
  null,
  'solution_organization',
  1,
  'ما الترتيب الصحيح لحل مسألة فيزيائية؟',
  '[{"id":"A","text":"استخراج المعطيات ← تحديد المطلوب ← اختيار القانون ← التعويض ← التحقق","diagnostic_tag":null},{"id":"B","text":"اختيار القانون ثم استخراج المعطيات","diagnostic_tag":"formula_first_order"},{"id":"C","text":"الحساب المباشر ثم تحديد المطلوب","diagnostic_tag":"calculation_before_problem"},{"id":"D","text":"التعويض العشوائي ثم التحقق لما يصادف","diagnostic_tag":"random_substitution"}]'::jsonb,
  'A',
  'المنهجية السليمة تبدأ بفهم المعطيات والمطلوب قبل اختيار القانون المناسب والتعويض ثم التحقق.',
  '["solution_steps","methodology","organization"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-012',
  'bac-physics-v1',
  'single_choice',
  'methodology',
  'methodology',
  'units',
  'unit_verification',
  1,
  'بعد إجراء حساب لطاقة، وجد الطالب النتيجة: E = 200 kg·m/s. ما الحكم الصحيح على هذه النتيجة؟',
  '[{"id":"A","text":"الوحدة غير متجانسة مع الطاقة، فالنتيجة خاطئة","diagnostic_tag":null},{"id":"B","text":"النتيجة صحيحة لأن العدد 200 معقول","diagnostic_tag":"number_focus_only"},{"id":"C","text":"الوحدة صحيحة لأنها وحدة سرعة","diagnostic_tag":"unit_for_velocity"},{"id":"D","text":"لا يمكن الحكم من الوحدات وحدها","diagnostic_tag":"dimensional_check_ignored"}]'::jsonb,
  'A',
  'الطاقة تقاس بالجول J = kg·m²/s². الوحدة الناتجة kg·m/s هي وحدة كمية حركة، فمصدرها خطأ في الحل.',
  '["unit_verification","dimensional_analysis","verify_result"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-027',
  'bac-physics-v1',
  'single_choice',
  'methodology',
  'methodology',
  null,
  'plausibility_check',
  2,
  'وجد طالب في حل مسألة أن سرعة سيارة تساوي 1080 km/h. ما الصواب في تقييم هذه النتيجة؟',
  '[{"id":"A","text":"ليست معقولة فيزيائيًا وعليه مراجعة الحساب","diagnostic_tag":null},{"id":"B","text":"معقولة لأن الحساب الرياضي سليم","diagnostic_tag":"math_over_physics"},{"id":"C","text":"لا يمكن الحكم دون مخطط","diagnostic_tag":"no_evaluation"},{"id":"D","text":"معقولة إن كانت الطريق سريعة","diagnostic_tag":"context_irrelevant"}]'::jsonb,
  'A',
  '1080 km/h = 300 m/s تقارب سرعة الصوت، وهي غير واقعية لسيارة؛ تحقق معقولية النتيجة جزء من المنهجية.',
  '["plausibility_check","result_verification","real_world_sense"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHY-DIAG-038',
  'bac-physics-v1',
  'single_choice',
  'methodology',
  'methodology',
  'concepts',
  'logical_reasoning',
  3,
  'الاستدلال: "بما أن سرعة الجسم ثابتة إذن محصلة القوى المطبقة عليه معدومة". أي عبارة صحيحة؟',
  '[{"id":"A","text":"الاستدلال صحيح إذا كانت الحركة مستقيمة","diagnostic_tag":null},{"id":"B","text":"الاستدلال صحيح مهما كان شكل المسار","diagnostic_tag":"circular_motion_overlooked"},{"id":"C","text":"الاستدلال خاطئ دائمًا","diagnostic_tag":"always_false"},{"id":"D","text":"الاستدلال صحيح فقط في السقوط الحر","diagnostic_tag":"condition_misplaced"}]'::jsonb,
  'A',
  'ثبات السرعة (كمية قياسية) لا يكفي لاستنتاج انعدام المحصلة؛ فالحركة الدائرية المنتظمة ثابتة السرعة ومحصلة قواها غير معدومة. الاستدلال صحيح للحركة المستقيمة المنتظمة.',
  '["logical_inference","newton_laws","speed_vs_velocity","circular_motion"]'::jsonb,
  1
);
