-- ============================================================
-- Migration 010: Seed diagnostic v2 question bank (bac-physics-v2)
-- Generated by scripts/build-diagnostic-v2-seed.js — DO NOT EDIT.
-- Source of truth: scripts/question-bank-v2.js
-- ============================================================

-- Retire the v1 bank: v2 becomes the active diagnostic test.
update public.diagnostic_tests set is_active = false where id = 'bac-physics-v1';

insert into public.diagnostic_tests (id, title, description, subject, grade, version, question_bank_version, total_questions, time_limit_minutes, is_active)
values (
  'bac-physics-v2',
  'اختبار تحديد المستوى التشخيصي في الفيزياء',
  'اختبار تشخيصي من 50 سؤالاً لطلاب البكالوريا في الفيزياء. يقيس المكتسبات السابقة والمهارات الرياضية والفيزيائية والتفكير العلمي دون افتراض معرفة دروس السنة الحالية، ويصدر ملفاً تشخيصياً مفصلاً ومساراً تعليمياً موصى به.',
  'physics',
  'baccalaureate',
  1,
  '2026-09-bac-physics-v2',
  50,
  75,
  true
)
on conflict (id) do update set title = excluded.title, description = excluded.description, version = excluded.version, question_bank_version = excluded.question_bank_version, total_questions = excluded.total_questions, time_limit_minutes = excluded.time_limit_minutes, is_active = excluded.is_active;

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-001',
  'bac-physics-v2',
  'single_choice',
  'mat-num',
  'mat-num',
  null,
  'mat-num',
  1,
  'اكتب العدد 0.000052 بالكتابة العلمية.',
  '[{"id":"A","text":"5.2 × 10⁻⁵","diagnostic_error":null},{"id":"B","text":"5.2 × 10⁻⁴","diagnostic_error":"اتجاه تحريك الفاصلة خاطئ رقم واحد"},{"id":"C","text":"52 × 10⁻⁶","diagnostic_error":"كتابة غير علمية (الجزء قبل الفاصلة أكبر من 10)"},{"id":"D","text":"5.2 × 10⁵","diagnostic_error":"عكس اتجاه تحريك الفاصلة (أس موجب)"}]'::jsonb,
  'A',
  '0.000052: نحرك الفاصلة 5 خانات نحو اليمين فيكون الأس −5: 5.2×10⁻⁵.',
  '["scientific_notation","exponent_sign","decimal_shift"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-002',
  'bac-physics-v2',
  'single_choice',
  'mat-num',
  'mat-num',
  'mat-unitconv',
  'mat-num',
  1,
  'قيمة 10⁻⁶ مألوفة في فيزياء الكميات الصغيرة. أي سابقة مقابلة؟',
  '[{"id":"A","text":"ميكرو (µ)","diagnostic_error":null},{"id":"B","text":"نانو (n)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻⁹"},{"id":"C","text":"ميلي (m)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻³"},{"id":"D","text":"بيكو (p)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻¹²"}]'::jsonb,
  'A',
  'السوابق: ميكرو µ=10⁻⁶، نانو n=10⁻⁹، ميلي m=10⁻³، بيكو p=10⁻¹².',
  '["si_prefix","powers_of_ten"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-003',
  'bac-physics-v2',
  'single_choice',
  'mat-num',
  'mat-num',
  null,
  'mat-num',
  2,
  'احسب: (2 × 10³) × (4 × 10⁻²)',
  '[{"id":"A","text":"80","diagnostic_error":null},{"id":"B","text":"800000 (8 × 10⁵)","diagnostic_error":"جمع الأسس بإشارة موجبة (3+2=5) بدل (3+(−2)=1)"},{"id":"C","text":"8","diagnostic_error":"نسيان ضرب الأعداد (2×4=8 صحيح لكن أخطأ في الأس)"},{"id":"D","text":"800","diagnostic_error":"خطأ في إشارة الأس عند الضرب"}]'::jsonb,
  'A',
  'نضرب الأعداد (2×4=8) ونجمع الأسس: 10^(3+(−2))=10¹، أي 80.',
  '["multiply_powers","exponent_addition"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-004',
  'bac-physics-v2',
  'single_choice',
  'mat-num',
  'mat-num',
  null,
  'mat-num',
  2,
  'احسب: (8 × 10⁶) ÷ (2 × 10⁻²)',
  '[{"id":"A","text":"4 × 10⁸","diagnostic_error":null},{"id":"B","text":"4 × 10⁴","diagnostic_error":"جمع الأسس بدلاً من طرحها (6−2 بدل 6+2)"},{"id":"C","text":"16 × 10⁸","diagnostic_error":"ضرب الأعداد بدل القسمة"},{"id":"D","text":"4 × 10⁻⁸","diagnostic_error":"خطأ في إشارة الأس الناتج"}]'::jsonb,
  'A',
  '8÷2=4 وللقسمة نطرح الأسس: 10^(6−(−2))=10⁸، أي 4×10⁸.',
  '["divide_powers","exponent_subtraction"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-005',
  'bac-physics-v2',
  'single_choice',
  'mat-unitconv',
  'mat-unitconv',
  null,
  'mat-unitconv',
  1,
  'حوّل 72 km/h إلى m/s.',
  '[{"id":"A","text":"20 m/s","diagnostic_error":null},{"id":"B","text":"259.2 m/s","diagnostic_error":"ضرب بـ 3.6 بدل القسمة"},{"id":"C","text":"36 m/s","diagnostic_error":"القسمة على 2 بدل 3.6"},{"id":"D","text":"72 m/s","diagnostic_error":"عدم التحويل (ترك الوحدة) والنظام غير SI"}]'::jsonb,
  'A',
  'التحويل من km/h إلى m/s يكون بالقسمة على 3.6: 72/3.6 = 20 m/s.',
  '["speed_conversion","kmh_to_ms"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-006',
  'bac-physics-v2',
  'single_choice',
  'mat-unitconv',
  'mat-unitconv',
  null,
  'mat-unitconv',
  2,
  'ما قيمة 250 cm³ بوحدة اللتر (L)؟',
  '[{"id":"A","text":"0.25 L","diagnostic_error":null},{"id":"B","text":"2.5 L","diagnostic_error":"الخلط بين cm³ و mL"},{"id":"C","text":"25 L","diagnostic_error":"الاعتقاد أن 1 L = 10 cm³"},{"id":"D","text":"250000 L","diagnostic_error":"عكس اتجاه التحويل (ضرب بـ 1000 بدل قسمته)"}]'::jsonb,
  'A',
  '1 L = 1 dm³ = 1000 cm³، إذن 250 cm³ = 250/1000 = 0.25 L.',
  '["volume_conversion","liter_cm3"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-007',
  'bac-physics-v2',
  'single_choice',
  'mat-unitconv',
  'mat-unitconv',
  'mat-num',
  'mat-unitconv',
  2,
  'عبر عن 1.66 × 10⁻²⁷ kg (كتلة الوحدة الذرية تقريباً) بالميجاغرام (Mg) علمياً نتائجك بالكتابة العلمية.',
  '[{"id":"A","text":"1.66 × 10⁻³⁰ Mg","diagnostic_error":null},{"id":"B","text":"1.66 × 10⁻²⁴ Mg","diagnostic_error":"استعمال 10³ بدل 10⁶"},{"id":"C","text":"1.66 × 10⁻²⁷ Mg","diagnostic_error":"عدم اعتبار معامل التحويل (اعتبر kg = Mg)"},{"id":"D","text":"1.66 × 10⁹ Mg","diagnostic_error":"عكس اتجاه التحويل"}]'::jsonb,
  'A',
  '1 Mg = 10⁶ g = 10³ kg، إذن 1.66×10⁻²⁷ kg = 1.66×10⁻²⁷ / 10³ = 1.66×10⁻³⁰ Mg.',
  '["mass_conversion","prefix_10_6"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-008',
  'bac-physics-v2',
  'single_choice',
  'mat-unitconv',
  'mat-unitconv',
  'mat-algebra',
  'mat-unitconv',
  3,
  'في العلاقات النووية يواجه المتعلم تحويلات مثل: 1 uma = 1.66054×10⁻²⁷ kg و 1 eV = 1.6×10⁻¹⁹ J. باستعمال علاقة التكافؤ E = m·c²، عبر عن 1 uma بوحدة MeV (علماً أن 1 MeV = 10⁶ eV، و c² ≈ 9×10¹⁶ m²/s²).',
  '[{"id":"A","text":"≈ 931 MeV","diagnostic_error":null},{"id":"B","text":"≈ 9.31 MeV","diagnostic_error":"النقص بعامل 10² في الحساب"},{"id":"C","text":"≈ 9.31×10⁻¹⁰ MeV","diagnostic_error":"الخلط بين التحويل إلى J والتحويل إلى MeV"},{"id":"D","text":"≈ 931 × 10⁶ MeV","diagnostic_error":"عدم القسمة على 10⁶ بعد التحويل إلى eV"}]'::jsonb,
  'A',
  'E = m·c² = 1.66054×10⁻²⁷ × 9×10¹⁶ ≈ 1.4945×10⁻¹⁰ J، ثم نحول إلى eV بقسمة 1.6×10⁻¹⁹: ≈ 9.34×10⁸ eV ≈ 934 MeV ≈ 931 MeV.',
  '["energy_conversion","amu_mev","c_squared"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-009',
  'bac-physics-v2',
  'single_choice',
  'mat-algebra',
  'mat-algebra',
  null,
  'mat-algebra',
  2,
  'من العلاقة n = m/M، عبر عن الكتلة m.',
  '[{"id":"A","text":"m = n × M","diagnostic_error":null},{"id":"B","text":"m = M / n","diagnostic_error":"قلب العلاقة (القسمة المعكوسة)"},{"id":"C","text":"m = n / M","diagnostic_error":"اعتبار n محلّى مباشرة بدون عزل"},{"id":"D","text":"m = M − n","diagnostic_error":"خلط الجبر (الجمع بدل الضرب)"}]'::jsonb,
  'A',
  'n = m/M ⇒ اضرب الطرفين في M: m = n × M.',
  '["isolate_variable","multiply_both_sides"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-010',
  'bac-physics-v2',
  'single_choice',
  'mat-algebra',
  'mat-algebra',
  'mat-logexp',
  'mat-algebra',
  2,
  'من العلاقة t½ = ln2/λ، عبر عن ثابت التفكك λ.',
  '[{"id":"A","text":"λ = ln2 / t½","diagnostic_error":null},{"id":"B","text":"λ = t½ / ln2","diagnostic_error":"قلب النسبة (البسط والمقام انعكسا)"},{"id":"C","text":"λ = t½ × ln2","diagnostic_error":"اعتبار الجداء بدل القسمة"},{"id":"D","text":"λ = ln2 × t½","diagnostic_error":"عدم إعادة (الضرب لكن بتعويض خاطئ)"}]'::jsonb,
  'A',
  't½ = ln2/λ ⇒ بضرب الطرفين في λ: λ·t½ = ln2 ⇒ λ = ln2/t½.',
  '["isolate_variable","fraction_solve"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-011',
  'bac-physics-v2',
  'single_choice',
  'mat-algebra',
  'mat-algebra',
  'mat-proportion',
  'mat-algebra',
  3,
  'علاقة التمديد: C₁·V₁ = C₂·V₂، ومعامل التمديد F = C₁/C₂. عبر عن F بدلالة الحجمين فقط.',
  '[{"id":"A","text":"F = V₂ / V₁","diagnostic_error":null},{"id":"B","text":"F = V₁ / V₂","diagnostic_error":"قلب النسبة في تعويض C₁/C₂"},{"id":"C","text":"F = V₂ − V₁","diagnostic_error":"طرح الحجوم بدل قسمتها"},{"id":"D","text":"F = V₁ × V₂","diagnostic_error":"جداء الحجوم بدل القسمة"}]'::jsonb,
  'A',
  'من C₁V₁=C₂V₂ نجد C₁/C₂ = V₂/V₁، أي F = V₂/V₁.',
  '["rearrange","ratio_conversion"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-012',
  'bac-physics-v2',
  'single_choice',
  'mat-algebra',
  'mat-algebra',
  'mat-num',
  'mat-algebra',
  4,
  'السرعة المدارية لقمر: v = √(G·M/r) مع G = 6.67×10⁻¹¹ (وحدات SI) و M = 6×10²⁴ kg و r = 4×10⁷ m. احسب v (بالتقريب).',
  '[{"id":"A","text":"≈ 3160 m/s","diagnostic_error":null},{"id":"B","text":"≈ 10⁷ m/s","diagnostic_error":"نسيان الجذر التربيعي"},{"id":"C","text":"≈ 100 m/s","diagnostic_error":"خطأ في قوى العدد 10 داخل المقدار"},{"id":"D","text":"≈ 316 m/s","diagnostic_error":"خطأ في حساب الجذر (ناقص صفر)"}]'::jsonb,
  'A',
  'G·M/r = (6.67×10⁻¹¹ × 6×10²⁴)/4×10⁷ = 4×10¹³/4×10⁷ = 10⁶، وجذر 10⁶ = 10³، مع 6.67×6/4 ≈ 10، أي v ≈ √(10×10⁶) ≈ 3160 m/s.',
  '["square_root","combine_powers","orbital_speed"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-013',
  'bac-physics-v2',
  'single_choice',
  'mat-proportion',
  'mat-proportion',
  null,
  'mat-proportion',
  1,
  '25% من كمية مقدارها 80 mol تساوي:',
  '[{"id":"A","text":"20 mol","diagnostic_error":null},{"id":"B","text":"25 mol","diagnostic_error":"اعتبار النسبة كمية مباشرة"},{"id":"C","text":"55 mol","diagnostic_error":"حساب المتبقي بدل النسبة"},{"id":"D","text":"4 mol","diagnostic_error":"قسمة 80 على 25 بدل الضرب في 0.25"}]'::jsonb,
  'A',
  '25% = 0.25، إذن 0.25 × 80 = 20 mol.',
  '["percentage","multiplication"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-014',
  'bac-physics-v2',
  'single_choice',
  'mat-proportion',
  'mat-proportion',
  'phy-lawapply',
  'mat-proportion',
  2,
  'قانون التناقص الإشعاعي: إذا بقي بعد مرور زمن t نصفُ العدد الابتدائي فقط (N = N₀/2)، فما النسبة المئوية المتبقية بعد مرور زمن 2t؟ (الانحلال متكرر بنصفين)',
  '[{"id":"A","text":"25%","diagnostic_error":null},{"id":"B","text":"0%","diagnostic_error":"اعتبار الانحلال خطياً (ينفد تماماً)"},{"id":"C","text":"50%","diagnostic_error":"عدم تكرار التنصيف (تطبيق نصف واحد فقط)"},{"id":"D","text":"75%","diagnostic_error":"اعتبار المتبقي يزداد نسبةً خطية"}]'::jsonb,
  'A',
  'كل نصف عمر يبقي النصف: بعد 2t يبقى ½×½ = ¼ = 25%.',
  '["halving","repeated_ratio"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-015',
  'bac-physics-v2',
  'single_choice',
  'mat-proportion',
  'mat-proportion',
  'mat-algebra',
  'mat-proportion',
  3,
  'جدول التقدم لتفاعل: A تأهباً، n(A) = n₀ − x. إذا كانت كمية المادة الابتدائية n₀ = 0.4 mol والمتقدم النهائي x_f = 0.3 mol، فما نسبة التقدم النهائي τf = x_f/x_max إذا كان x_max = 0.4 mol؟',
  '[{"id":"A","text":"0.75","diagnostic_error":null},{"id":"B","text":"0.25","diagnostic_error":"حساب (0.4−0.3)/0.4 بدل x_f/x_max"},{"id":"C","text":"1.33","diagnostic_error":"قلب النسبة (x_max/x_f)"},{"id":"D","text":"0.3","diagnostic_error":"استعمال x_f وحده بدل النسبة"}]'::jsonb,
  'A',
  'τf = x_f/x_max = 0.3/0.4 = 0.75.',
  '["advancement_ratio","fraction"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-016',
  'bac-physics-v2',
  'single_choice',
  'mat-proportion',
  'mat-proportion',
  'phy-graph',
  'mat-proportion',
  4,
  'قانون كبلر الثالث: T² = k·r³ (r نصف المحور الأكبر). إذا تضاعف نصف المحور r، فكيف يتغير الزمن الدوري T؟',
  '[{"id":"A","text":"يتضاعف بنحو 2.8 (× 2√2)","diagnostic_error":null},{"id":"B","text":"يتضاعف تماماً (×2)","diagnostic_error":"اعتبار T∝r مباشرة بدون الجذر"},{"id":"C","text":"يتضاعف أربع مرات (×4)","diagnostic_error":"الخلط بين T² و T"},{"id":"D","text":"لا يتغير","diagnostic_error":"تجاهل اعتماد T على r"}]'::jsonb,
  'A',
  'T = √(k·r³): إذا تضاعف r يصبح T'' = √(k·(2r)³) = √(8·k·r³) = √8 · T ≈ 2.83 T.',
  '["power_law","cube_root_behaviour"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-017',
  'bac-physics-v2',
  'single_choice',
  'mat-logexp',
  'mat-logexp',
  null,
  'mat-logexp',
  2,
  'احسب ln(e²) ثم ln(1).',
  '[{"id":"A","text":"2 ثم 0","diagnostic_error":null},{"id":"B","text":"e² ثم 1","diagnostic_error":"الخلط بين الدالة وعكسها"},{"id":"C","text":"2 ثم 1","diagnostic_error":"الاعتقاد ln(1) = 1"},{"id":"D","text":"0 ثم 2","diagnostic_error":"عكس الموضعين (التبديل)"}]'::jsonb,
  'A',
  'ln(e^x) = x، إذن ln(e²) = 2، و ln(1) = 0 لأن e⁰ = 1.',
  '["natural_log","inverse_exp"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-018',
  'bac-physics-v2',
  'single_choice',
  'mat-logexp',
  'mat-logexp',
  null,
  'mat-logexp',
  2,
  'علاقة pH = −log[H₃O⁺]. محاليل مائية نقي التركيز [H₃O⁺] = 0.001 mol/L و [OH⁻] معه. احسب pH (لاحظ log(10⁻³) = −3).',
  '[{"id":"A","text":"pH = 3","diagnostic_error":null},{"id":"B","text":"pH = −3","diagnostic_error":"الخلط بين pH و[H₃O⁺] بعلامة"},{"id":"C","text":"pH = 0.001","diagnostic_error":"إرجاع التركيز مباشرة دون لوغاريتم"},{"id":"D","text":"pH = 11","diagnostic_error":"حساب pOH بدل pH"}]'::jsonb,
  'A',
  'pH = −log(10⁻³) = −(−3) = 3.',
  '["ph_scale","log10_scale"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-019',
  'bac-physics-v2',
  'single_choice',
  'mat-logexp',
  'mat-logexp',
  'rea-justify',
  'mat-logexp',
  3,
  'مقدار يتناقص أسياً: y(t) = y₀·e^(−t/τ). عند اللحظة t = τ، ما قيمة y بالعلاقة مع y₀ (تذكر eⁿ ≈ 2.72)؟',
  '[{"id":"A","text":"y ≈ y₀ / 2.72 (أي ≈ 0.37 y₀)","diagnostic_error":null},{"id":"B","text":"y = y₀ / 2","diagnostic_error":"الخلط مع نصف العمر (الأس × ln2)"},{"id":"C","text":"y = y₀","diagnostic_error":"اعتبار e^(−1) قريب من 1"},{"id":"D","text":"y = 0","diagnostic_error":"اعتبار التناقص الأسّي وصولاً للصفر عند t=τ"}]'::jsonb,
  'A',
  'y(τ) = y₀·e^(−1) = y₀/e ≈ y₀/2.72 ≈ 0.37 y₀. (هذا أصل طريقة 37% في تفريغ المكثفة).',
  '["exponential_decay","tau_37_percent"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-020',
  'bac-physics-v2',
  'single_choice',
  'mat-logexp',
  'mat-logexp',
  'mat-algebra',
  'mat-logexp',
  4,
  'قانون التفكك: N(t) = N₀·e^(−λt). تريد حساب زمن التأريخ t حيث يبقى N = N₀/4. عبر عن t (استعمل ln).',
  '[{"id":"A","text":"t = ln4 / λ","diagnostic_error":null},{"id":"B","text":"t = ln(1/4) / λ = −ln4/λ","diagnostic_error":"علامة سالبة في البسط رغم أن t زمن موجب"},{"id":"C","text":"t = λ · ln4","diagnostic_error":"لا عزل صحيح (المقام والبسط انقلبا)"},{"id":"D","text":"t = ln(4/1) · λ","diagnostic_error":"خلط بين ln والضرب في λ"}]'::jsonb,
  'A',
  'N₀/4 = N₀e^(−λt) ⇒ e^(−λt) = 1/4 ⇒ −λt = ln(1/4) = −ln4 ⇒ t = ln4/λ.',
  '["logarithm_solve","decay_dating"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-021',
  'bac-physics-v2',
  'single_choice',
  'mat-calc',
  'mat-calc',
  'phy-graph',
  'mat-calc',
  2,
  'ما اشتقاق الدالة x(t) = 5t + 3 بالنسبة للزمن t؟',
  '[{"id":"A","text":"dx/dt = 5","diagnostic_error":null},{"id":"B","text":"dx/dt = 5t","diagnostic_error":"نسيان أن اشتقاق t يساوي 1"},{"id":"C","text":"dx/dt = 5 + 3t","diagnostic_error":"اشتقاق الثابت 3 كأنه متغير"},{"id":"D","text":"dx/dt = 5t²/2 + 3t","diagnostic_error":"التكامل بدل الاشتقاق (قاعدة معكوسة)"}]'::jsonb,
  'A',
  'اشتقاق 5t هو 5 (ثابت)، واشتقاق الثابت 3 هو 0: النتيجة 5.',
  '["derivative_polynomial","constant_rule"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-022',
  'bac-physics-v2',
  'single_choice',
  'mat-calc',
  'mat-calc',
  'phy-graph',
  'mat-calc',
  3,
  'سرعة التفاعل في المتابعة الزمنية هي v = dx/dt. إذا كان المنحنى x(t) مماسٌ له ميل يساوي 0.02 mol/s عند اللحظة t₀، فما معنى هذه القيمة؟',
  '[{"id":"A","text":"السرعة اللحظية للتفاعل عند t₀ = 0.02 mol/s","diagnostic_error":null},{"id":"B","text":"التقدم المنجز حتى t₀ هو 0.02 mol","diagnostic_error":"خلط الميل مع قيمة x نفسها"},{"id":"C","text":"زمن نصف التفاعل 0.02 s","diagnostic_error":"خلط وحدات الميل مع زمن"},{"id":"D","text":"السرعة المتوسطة على كامل التجربة","diagnostic_error":"الخلط بين السرعة اللحظية والمتوسطة"}]'::jsonb,
  'A',
  'ميل المماس لمنحنى x(t) عند لحظة يعطي قيمة المشتقة dx/dt أي السرعة اللحظية عند تلك اللحظة.',
  '["slope_meaning","instantaneous_rate"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-023',
  'bac-physics-v2',
  'single_choice',
  'mat-calc',
  'mat-calc',
  'phy-graph',
  'mat-calc',
  4,
  'من جملة السرعة: v(t) = 2t + 1 (m/s). ما المسافة المقطوعة بين t = 0 و t = 3 s؟ (المسافة = مساحة سطح تحت منحنى v(t)، والناتج بالتكامل)',
  '[{"id":"A","text":"12 m","diagnostic_error":null},{"id":"B","text":"7 m","diagnostic_error":"حساب v(3) فقط بدل المساحة"},{"id":"C","text":"6 m","diagnostic_error":"حساب مساحة مستطيل (سرعة متوسطة مفترضة)"},{"id":"D","text":"18 m","diagnostic_error":"التكامل مع نسيان الثابت (استعمال 2t² وحده)"}]'::jsonb,
  'A',
  'المسافة = ∫₀³(2t+1)dt = [t²+t]₀³ = 9+3 = 12 m.',
  '["definite_integral","area_under_curve"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-024',
  'bac-physics-v2',
  'single_choice',
  'mat-vectrig',
  'mat-vectrig',
  null,
  'mat-vectrig',
  2,
  'مركبتا شعاع السرعة: vx = 6 m/s و vy = 8 m/s. احسب معيار السرعة |v| = √(vx² + vy²).',
  '[{"id":"A","text":"10 m/s","diagnostic_error":null},{"id":"B","text":"14 m/s","diagnostic_error":"جمع المركبتين مباشرة (6+8)"},{"id":"C","text":"48 m/s","diagnostic_error":"الضرب قبل الجذر (6×8)"},{"id":"D","text":"2 m/s","diagnostic_error":"الفرق بين المركبتين (8−6)"}]'::jsonb,
  'A',
  '|v| = √(36+64) = √100 = 10 m/s.',
  '["vector_magnitude","pythagoras"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-025',
  'bac-physics-v2',
  'single_choice',
  'mat-vectrig',
  'mat-vectrig',
  null,
  'mat-vectrig',
  3,
  'شعاع سرعة مقدار v₀ = 20 m/s مُمال بزاوية α = 60° مع الأفقي. احسب المركبة العمودية v₀·sin(60°) (تذكر sin60° ≈ 0.87).',
  '[{"id":"A","text":"≈ 17.3 m/s","diagnostic_error":null},{"id":"B","text":"≈ 10 m/s","diagnostic_error":"استعمال cos60° بدل sin60° (المركبة الأفريقية)"},{"id":"C","text":"≈ 20 m/s","diagnostic_error":"اعتبار المركبة تساوي المعيار مباشرة"},{"id":"D","text":"≈ 34.6 m/s","diagnostic_error":"ضرب خاطئ (20 × 1.73)"}]'::jsonb,
  'A',
  'v₀z = v₀·sin60° = 20 × 0.87 ≈ 17.3 m/s.',
  '["sine_projection","oblique_throw"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-026',
  'bac-physics-v2',
  'single_choice',
  'mat-vectrig',
  'mat-vectrig',
  'phy-lawapply',
  'mat-vectrig',
  4,
  'على مستوي مائل بزاوية α مع الأفقي، يُسقط وزن جسم P على المحور الموازي للمستوي فيعطي المركبة P·sinα. إذا كان P = 100 N و α = 30° (sin30° = 0.5)، فما قيمة هذه المركبة؟',
  '[{"id":"A","text":"50 N","diagnostic_error":null},{"id":"B","text":"100 N","diagnostic_error":"اعتبار المركبة تساوي الوزن (زاوية 90°) للخطأ"},{"id":"C","text":"86.6 N","diagnostic_error":"استعمال cos30° بدل sin30°"},{"id":"D","text":"12.5 N","diagnostic_error":"جداء خاطئ (100 × 0.5 / 4)"}]'::jsonb,
  'A',
  'P·sinα = 100 × 0.5 = 50 N — هذا أصل حركة جسم فوق مستوي مائل.',
  '["inclined_plane","inclined_plane_component"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-027',
  'bac-physics-v2',
  'single_choice',
  'phy-graph',
  'phy-graph',
  'mat-calc',
  'phy-graph',
  2,
  'منحنى x(t) لحركة مستقيمة هو خط مستقيم يمر بالنقطتين (2, 8) و(6, 20) مع x بالمتر وt بالثانية. ما ميل الخط (أي السرعة الثابتة)؟',
  '[{"id":"A","text":"3 m/s","diagnostic_error":null},{"id":"B","text":"2 m/s","diagnostic_error":"خطأ حسابي في الفرق (20−8=12، ÷(6−2)=4)"},{"id":"C","text":"4 m/s","diagnostic_error":"حساب الميل كما Δx/Δt لكن أخطأ في الفرقة (8/2)"},{"id":"D","text":"12 m/s","diagnostic_error":"استعمال Δx فقط دون القسمة على Δt"}]'::jsonb,
  'A',
  'الميل = (20−8)/(6−2) = 12/4 = 3 m/s.',
  '["linear_slope","speed_from_graph"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-028',
  'bac-physics-v2',
  'single_choice',
  'phy-graph',
  'phy-graph',
  null,
  'phy-graph',
  3,
  'لاختيار طريقة بيانية بديلة، نرسم ln(N) بدلالة t فنجد خطاً مستقيماً. إذا كان الميل = −0.04 (وحدة s⁻¹)، فما قيمة ثابت التفكك λ (بعلاقة N = N₀e^(−λt))؟',
  '[{"id":"A","text":"λ = 0.04 s⁻¹","diagnostic_error":null},{"id":"B","text":"λ = −0.04 s⁻¹","diagnostic_error":"الجمع المباشر للعلامة السالبة في λ"},{"id":"C","text":"λ = e^0.04 s⁻¹","diagnostic_error":"الخلط بين ln والتجزيء"},{"id":"D","text":"λ = 1/0.04 s⁻¹","diagnostic_error":"قلب العلاقة (اعتبار tan(θ)=1/λ)"}]'::jsonb,
  'A',
  'بأخذ ln: lnN = lnN₀ − λt، فميل المستقيم = −λ، إذن λ = 0.04 s⁻¹.',
  '["linearization","ln_graph_slope"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-029',
  'bac-physics-v2',
  'single_choice',
  'phy-graph',
  'phy-graph',
  'mat-logexp',
  'phy-graph',
  3,
  'منحنى شحن مكثفة uC(t) يقترب أسياً من القيمة النهائية E. عند الزمن المقابل لـ τ (ثابت الزمن) يصل uC إلى 63% من E. إذا كان E = 12 V و τ = 2 s، فماذا تكون uC عند t = 2 s تقريباً؟',
  '[{"id":"A","text":"≈ 7.6 V","diagnostic_error":null},{"id":"B","text":"≈ 12 V","diagnostic_error":"التوصل للقيمة النهائية فوراً (اعتبار τ = ∞)"},{"id":"C","text":"≈ 4.4 V","diagnostic_error":"حساب 37% بدل 63% (خلط شحن/تفريغ)"},{"id":"D","text":"≈ 0 V","diagnostic_error":"اعتبار المكثفة فارغة عند τ"}]'::jsonb,
  'A',
  'عند t = τ: uC = 0.63 × E = 0.63 × 12 ≈ 7.6 V.',
  '["time_constant_63","rc_charging_curve"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-030',
  'bac-physics-v2',
  'single_choice',
  'phy-graph',
  'phy-graph',
  'phy-table',
  'phy-graph',
  4,
  'منحنى v(t) للسقوط الحر v = 10t (m/s). المسافة المقطوعة خلال أول 5 ثوانٍ تساوي مساحة سطح تحت المنحنى وهي سطح مثلث. احسبها.',
  '[{"id":"A","text":"125 m","diagnostic_error":null},{"id":"B","text":"50 m","diagnostic_error":"مساحة المستطيل (القاعدة × العرض كأن v ثابتة)"},{"id":"C","text":"250 m","diagnostic_error":"مساحة المثلث بضرب القاعدة × الارتفاع بدون قسمة (×2)"},{"id":"D","text":"10 m","diagnostic_error":"استخلاص الارتفاع الواحد (v(1) فقط)"}]'::jsonb,
  'A',
  'المساحة = ½ × القاعدة(5s) × الارتفاع(v(5)=50 m/s) = ½×5×50 = 125 m.',
  '["triangle_area","distance_from_v_t"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-031',
  'bac-physics-v2',
  'single_choice',
  'phy-table',
  'phy-table',
  null,
  'phy-table',
  2,
  'جدول تتبع زمني لتحول كيميائي يعطي x (mmol) عند لحظات t (min): t=0→0، t=1→20، t=2→35، t=3→44، t=4→48، t=5→49. أي استنتاج صحيح؟',
  '[{"id":"A","text":"السرعة تتناقص مع الزمن حتى تقارب الصفر","diagnostic_error":null},{"id":"B","text":"السرعة ثابتة طوال التفاعل","diagnostic_error":"عدم ملاحظة تناقص زيادات x"},{"id":"C","text":"السرعة تزداد مع الزمن","diagnostic_error":"خلط زيادة x مع زيادة السرعة"},{"id":"D","text":"التفاعل سريع جداً وينتهي عند t=1","diagnostic_error":"اعتبار أول خطوة كل شيء"}]'::jsonb,
  'A',
  'الزيادات (20، 15، 9، 4، 1) تتناقص: السرعة (= التغير) تتناقص حتى تقارب الصفر قرب النهاية.',
  '["table_pattern","rate_decrease"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-032',
  'bac-physics-v2',
  'single_choice',
  'phy-table',
  'phy-table',
  'mat-proportion',
  'phy-table',
  3,
  'جدول التصوير المتعاقب لمتحرك يعطي المواضع عند فواصل زمنية ثابتة τ = 0.1 s: M0(0)، M1(0.01)، M2(0.04)، M3(0.09)، M4(0.16) بالمتر. ما طبيعة الحركة (يتصاعد الفارق بانتظام)؟',
  '[{"id":"A","text":"حركة متسارعة بانتظام","diagnostic_error":null},{"id":"B","text":"حركة منتظمة","diagnostic_error":"عدم ملاحظة تصاعد الفوارق"},{"id":"C","text":"حركة متباطئة","diagnostic_error":"عكس الاتجاه (خلط التسارع مع التباطؤ)"},{"id":"D","text":"حركة دائرية","diagnostic_error":"لا يمكن استنتاج من البيانات (إسقاط خاطئ)"}]'::jsonb,
  'A',
  'الأبعاد تتزايد بفرق: 0.01، 0.03، 0.05، 0.07 — الزيادة في كل فترة ثابتة (0.02) ⇒ تسارع ثابت ⇒ حركة متسارعة بانتظام.',
  '["sequential_frames","uniform_acceleration"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-033',
  'bac-physics-v2',
  'single_choice',
  'phy-unitsdim',
  'phy-unitsdim',
  'mat-unitconv',
  'phy-unitsdim',
  2,
  'باعتماد أن R تقاس بالأوم (Ω) و C بالفاراد (F)، وأن الجداء R·C يُستخدم كثابت زمن. ما وحدة الجداء R·C في النظام الدولي؟',
  '[{"id":"A","text":"الثانية (s)","diagnostic_error":null},{"id":"B","text":"الهيرتز (Hz)","diagnostic_error":"الخلط بين الزمن والتردد"},{"id":"C","text":"الفولت (V)","diagnostic_error":"خلط وحدات التوتر"},{"id":"D","text":"بلا أبعاد تماماً","diagnostic_error":"الاعتقاد أنه مجرد عدد"}]'::jsonb,
  'A',
  'التحليل البعدي: 1 Ω = 1 kg·m²/(A²·s³) و 1 F = 1 A²·s⁴/(kg·m²)، والجداء = s. أي [R·C] = [T].',
  '["dimensional_homogeneity","rc_time_constant"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-034',
  'bac-physics-v2',
  'single_choice',
  'phy-unitsdim',
  'phy-unitsdim',
  'mat-logexp',
  'phy-unitsdim',
  3,
  'نشاط مصدر مشع A = λ·N حيث λ ثابت تفكك وN عدد الأنوية (بدون وحدة). إذا قيس النشاط بـ Bq = تفكك/ثانية، فما وحدة λ؟',
  '[{"id":"A","text":"s⁻¹","diagnostic_error":null},{"id":"B","text":"Bq","diagnostic_error":"الخلط بين النشاط وثابت التفكك"},{"id":"C","text":"s","diagnostic_error":"الاعتقاد λ زمن (خلط مع τ=1/λ)"},{"id":"D","text":"جول (J)","diagnostic_error":"خلط وحدات الطاقة"}]'::jsonb,
  'A',
  'λ = A/N: وحدة النشاط على عدد بلا وحدة ⇒ وحدة λ هي s⁻¹.',
  '["unit_inference","activity_law"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-035',
  'bac-physics-v2',
  'single_choice',
  'phy-unitsdim',
  'phy-unitsdim',
  'mat-algebra',
  'phy-unitsdim',
  4,
  'قوة الاحتكاك f = K·v حيث v سرعة (m/s) و f قوة (N). بالتحليل البعدي، ما وحدة الثابت K في النظام الدولي؟ (N = kg·m/s²)',
  '[{"id":"A","text":"kg/s","diagnostic_error":null},{"id":"B","text":"kg·m/s²","diagnostic_error":"وحدة القوة نفسها (نسيان القسمة على السرعة)"},{"id":"C","text":"kg·m/s","diagnostic_error":"قسمة على v² بدل v"},{"id":"D","text":"بلا وحدات","diagnostic_error":"اعتبار K عدداً صرفاً"}]'::jsonb,
  'A',
  'K = f/v: (kg·m/s²)/(m/s) = kg/s.',
  '["viscous_force","derive_unit_from_formula"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-036',
  'bac-physics-v2',
  'single_choice',
  'phy-lawapply',
  'phy-lawapply',
  null,
  'phy-lawapply',
  1,
  'علاقة التركيز: C = n/V مع n = 1 mol و V = 2 L. احسب C.',
  '[{"id":"A","text":"0.5 mol/L","diagnostic_error":null},{"id":"B","text":"2 mol/L","diagnostic_error":"قلب النسبة (C = V/n)"},{"id":"C","text":"3 mol/L","diagnostic_error":"جمع بدل قسمة"},{"id":"D","text":"1 mol/L","diagnostic_error":"استعمال n وحده دون القسمة على الحجم"}]'::jsonb,
  'A',
  'توظيف مباشر: C = 1/2 = 0.5 mol/L.',
  '["apply_relation","molar_concentration"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-037',
  'bac-physics-v2',
  'single_choice',
  'phy-lawapply',
  'phy-lawapply',
  'mat-unitconv',
  'phy-lawapply',
  2,
  'قانون الغازات: n = P·V/(R·T) حيث P بالباسكال و V بالمتر³ و T بالكلفن. احسب n لكتلة غاز حيث P = 10⁵ Pa، V = 0.024 m³، T = 300 K، R = 8.31 J/(mol·K).',
  '[{"id":"A","text":"n ≈ 0.96 mol","diagnostic_error":null},{"id":"B","text":"n ≈ 1.04 × 10⁻² mol","diagnostic_error":"خطأ في العمود (ضرب T في R صحيح لكن مقام خاطئ)"},{"id":"C","text":"n ≈ 960 mol","diagnostic_error":"عدم القسمة على R·T (حساب P·V فقط)"},{"id":"D","text":"n ≈ 1.6 mol","diagnostic_error":"استعمال درجة الحرارة بالسلسيوس دون تحويل"}]'::jsonb,
  'A',
  'n = (10⁵ × 0.024) / (8.31 × 300) = 2400 / 2493 ≈ 0.96 mol.',
  '["ideal_gas","substitute_units"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-038',
  'bac-physics-v2',
  'single_choice',
  'phy-lawapply',
  'phy-lawapply',
  'mat-proportion',
  'phy-lawapply',
  3,
  'قانون المعايرة عند التكافؤ: Ca·Va = Cb·Vb. إذا كان Ca = 0.1 mol/L، Va = 20 mL، Cb = 0.05 mol/L، فما حجم الأساس Vb عند التكافؤ؟',
  '[{"id":"A","text":"40 mL","diagnostic_error":null},{"id":"B","text":"20 mL","diagnostic_error":"اعتبار Vb = Va (تجاهل تركيز Cb)"},{"id":"C","text":"10 mL","diagnostic_error":"خطأ في قلب النسبة (Vb = Ca·Cb·Va خطأ)"},{"id":"D","text":"100 mL","diagnostic_error":"نسيان التحويل إلى mL وعمل 0.1×20/0.05×1000"}]'::jsonb,
  'A',
  'Vb = Ca·Va/Cb = (0.1 × 20)/0.05 = 2/0.05 = 40 mL.',
  '["titration_equivalence","proportional"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-039',
  'bac-physics-v2',
  'single_choice',
  'phy-protocol',
  'phy-protocol',
  'rea-justify',
  'phy-protocol',
  2,
  'في المتابعة الزمنية بالمعايرة، لماذا توضع عينات التفاعل في (ماء بارد + جليد) قبل المعايرة؟',
  '[{"id":"A","text":"لإيقاف التفاعل عند اللحظة المرادة (سقي فيزيائي)","diagnostic_error":null},{"id":"B","text":"لتسريع التفاعل وبلوغ النهاية أسرع","diagnostic_error":"عكس التأثير الحراري (البرد يبطئ لا يسرع)"},{"id":"C","text":"لتغيير التركيب المولي النهائي","diagnostic_error":"الخلط بين السقي والتركيز"},{"id":"D","text":"لزيادة حجم التكافؤ V_E","diagnostic_error":"الاعتقاد أن السقي يؤثر على المصير النهائي (وهو لا يؤثر)"}]'::jsonb,
  'A',
  'التبريد المفاجئ (السقي) يوقف التفاعل دون تغيير كمية المادة؛ لا يؤثر على V_E ولا على التركيب النهائي.',
  '["quenching","kinetic_factor_temperature"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-040',
  'bac-physics-v2',
  'single_choice',
  'phy-protocol',
  'phy-protocol',
  'phy-table',
  'phy-protocol',
  3,
  'عند قياس الناقلية G = K·σ، فإن ثابت الخلية K له وحدة الطول (m) لأنه قسمة مساحة على مسافة (S/L). لماذا يُنتبه لتسجيل σ (الناقلية النوعية) وليس فقط G؟',
  '[{"id":"A","text":"لأن σ مستقلة عن شكل الخلية وتسمح بالحساب من التركيز عبر σ = Σλi·[Xi]","diagnostic_error":null},{"id":"B","text":"لأن G هي نفسها σ دائماً","diagnostic_error":"الخلط بين G وσ (يصمح K)"},{"id":"C","text":"لأن σ لا علاقة لها بالتركيز","diagnostic_error":"إنكار العلاقة σ مع التراكيز"},{"id":"D","text":"لأن قياس G مستحيل عملياً","diagnostic_error":"خطأ واقعي: G تقاس بمقياس الناقلية"}]'::jsonb,
  'A',
  'σ مرتبطة مباشرة بتراكيز الشوارد عبر الناقليات المولية، بينما G تعتمد على خلية القياس (K).',
  '["conductivity","cell_constant"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-041',
  'bac-physics-v2',
  'single_choice',
  'rea-method',
  'rea-method',
  null,
  'rea-method',
  1,
  'ما الترتيب الصحيح لحل مسألة فيزيائية؟',
  '[{"id":"A","text":"استخراج المعطيات ← تحديد المطلوب ← اختيار العلاقة ← التعويض ← التحقق","diagnostic_error":null},{"id":"B","text":"اختيار العلاقة أولاً ثم استخراج المعطيات","diagnostic_error":"اعتماد العلاقة قبل الفهم"},{"id":"C","text":"التعويض المباشر دون تحديد المطلوب","diagnostic_error":"إجراء بلا توجيه"},{"id":"D","text":"الحساب ثم المعطيات","diagnostic_error":"عكس المنهجية المعتمدة"}]'::jsonb,
  'A',
  'المنهجية الموثقة في كل الوحدات تبدأ بفهم المعطيات وتحديد المطلوب قبل اختيار العلاقة.',
  '["methodology_steps"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-042',
  'bac-physics-v2',
  'single_choice',
  'rea-method',
  'rea-method',
  null,
  'rea-method',
  2,
  'في مسألة: "يحتوي محلول على 5 g من صوديوم مذاب في 250 mL، احسب التركيز المولي مع العلم M = 23 g/mol". ما المعطيات الزائدة أو المفتقدة للتعويض؟',
  '[{"id":"A","text":"اكتمل كل المطلوب: m، V، M لاستعمال n=m/M ثم C=n/V","diagnostic_error":null},{"id":"B","text":"المعطيات ناقصة: نفتقد درجة الحرارة","diagnostic_error":"درجة الحرارة غير لازمة هنا"},{"id":"C","text":"المعطيات زائدة: M لا لزوم لها","diagnostic_error":"M ضرورية لحساب n"},{"id":"D","text":"المعطيات زائدة: V لا لزوم له","diagnostic_error":"V ضرورية لتحويل n إلى C"}]'::jsonb,
  'A',
  'المنهجية: المطلوب C؛ نستعمل m,M لنحسب n=m/M ثم نحول C=n/V (مع تحويل 250 mL إلى L).',
  '["data_filtering","two_step_calculation"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-043',
  'bac-physics-v2',
  'single_choice',
  'rea-method',
  'rea-method',
  'mat-unitconv',
  'rea-method',
  3,
  'قبل التعويض في علاقة، ما التحقق الأهم أولاً بعد التأكد من نوع الكمية؟',
  '[{"id":"A","text":"توحيد وحدات كل الكميات بالنظام الدولي (تحويل mL→L، g→kg...)","diagnostic_error":null},{"id":"B","text":"مضاعفة القيم لتسهيل الحساب","diagnostic_error":"تغيير المعطيات يخل بالنتيجة"},{"id":"C","text":"إهمال الوحدات لأن القيم أرقام فقط","diagnostic_error":"الوحدات جوهرية للتحقق"},{"id":"D","text":"استعمال الوحدات غير الرسمية كما هي","diagnostic_error":"يؤدي غالباً لنتيجة خاطئة"}]'::jsonb,
  'A',
  'التحقق البعدي/الوحدي أولاً: التجانس مسبق للتعويض به يضمن نتيجة صحيحة الأبعاد.',
  '["unit_inspection","pre_substitution"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-044',
  'bac-physics-v2',
  'single_choice',
  'rea-justify',
  'rea-justify',
  'rea-compare',
  'rea-justify',
  2,
  'رفعنا درجة حرارة تفاعل بطيء. بعد التبريد عاد التفاعل بنفاد أسرع؟ ما التبرير الصحيح لتأثير الحرارة؟',
  '[{"id":"A","text":"الحرارة ترفع تواتر التصادمات الفعالة فتزداد السرعة وينقص t₁/₂","diagnostic_error":null},{"id":"B","text":"الحرارة تغير طبيعة التفاعل (تام بدل محدود)","diagnostic_error":"إذا كان تاماً يبقى تاماً"},{"id":"C","text":"الحرارة لا تأثير لها إطلاقاً","diagnostic_error":"إنكار عامل حركي"},{"id":"D","text":"الحرارة تستهلك المتفاعلات فتزيد كمية النواتج","diagnostic_error":"خلط العامل الحركي بالتركيب"}]'::jsonb,
  'A',
  'الحرارة عامل حركي: ترفع سرعة التفاعل بدون تغيير التركيب المولي النهائي (مع بقاء t₁/₂ ينقص).',
  '["kinetic_factor","temperature_effect"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-045',
  'bac-physics-v2',
  'single_choice',
  'rea-justify',
  'rea-justify',
  'mat-num',
  'rea-justify',
  3,
  'تتحول نواة X إلى نواة Y بإصدار إلكترون e⁻ (تفكك β⁻) حسب: ^(A)Z(X) → ^(A)(Z+1)(Y) + e⁻. أي مبدأ تحققوه هنا؟',
  '[{"id":"A","text":"انحفاظ العدد الكتلي A وانحفاظ العدد الذري Z","diagnostic_error":null},{"id":"B","text":"انحفاظ العدد الذري فقط","diagnostic_error":"نسيان انحفاظ A"},{"id":"C","text":"انحفاظ عدد النترونات N = A − Z","diagnostic_error":"انحفاظ A وZ لا يفرض انحفاظ N (N انعكس)"},{"id":"D","text":"لا انحفاظ يتطلب في التفاعلات النووية","diagnostic_error":"مبدأان دائماً محفوظان"}]'::jsonb,
  'A',
  'في كل التفاعلات النووية يتحقق انحفاظ العدد الكتلي والعدد الذري (فحص A: A=A+0، Z: Z=Z+1−1).',
  '["conservation_laws","beta_decay"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-046',
  'bac-physics-v2',
  'single_choice',
  'rea-justify',
  'rea-justify',
  'phy-graph',
  'rea-justify',
  4,
  'منحنى v(t) لجسم هو خط مستقيم متناقص يلتقي المحور الأفقي عند t = 6 s ثم يبقى عند v=0. أي استنتاج صحيح؟',
  '[{"id":"A","text":"حركة مستقيمة متباطئة حتى السكون ثم يستقر","diagnostic_error":null},{"id":"B","text":"حركة متسارعة بانتظام","diagnostic_error":"الميل سالب ثابت = تباطؤ لا تسارع"},{"id":"C","text":"حركة منتظمة","diagnostic_error":"الخط ليس أفقياً وسطياً"},{"id":"D","text":"الجسم يرتد ويغير اتجاهه","diagnostic_error":"لا دليل على انعكاس الاتجاه (v تبقى ≥0)"}]'::jsonb,
  'A',
  'ميل سالب ثابت ⇒ تباطؤ منتظم حتى v=0 عند t=6 ثم بقاء (سكون). (a·v < 0 حتى الصفر).',
  '["decreasing_slope","motion_type_inference"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-047',
  'bac-physics-v2',
  'single_choice',
  'rea-compare',
  'rea-compare',
  'mat-logexp',
  'rea-compare',
  3,
  'حمضان ضعيفان لهما نفس التركيز: حمض A ثابت Ka = 10⁻⁴ وحمض B ثابت Ka = 10⁻⁶. أي منهما الحمض الأقوى؟',
  '[{"id":"A","text":"A هو الأقوى (Ka أكبر ⇒ تفكك أكبر ⇒ τf أكبر و pH أصغر)","diagnostic_error":null},{"id":"B","text":"B هو الأقوى","diagnostic_error":"عكس منطق المقارنة عبر Ka"},{"id":"C","text":"متعادلان تماماً","diagnostic_error":"Ka مختلفان فهما لا يتعادلان"},{"id":"D","text":"لا يمكن الجواب بدون قياس pH","diagnostic_error":"Ka يعطي الجواب مباشرة للمقارنة"}]'::jsonb,
  'A',
  'كلما كبر Ka قوي الحمض: A (Ka=10⁻⁴ أكبر) فالأقوى (وبالتالي τf أكبر وpH أصغر).',
  '["acid_strength_compare","ka_order"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-048',
  'bac-physics-v2',
  'single_choice',
  'rea-compare',
  'rea-compare',
  'rea-justify',
  'rea-compare',
  5,
  'قارن القيم التالية لنواتين: نواة 1 ومقابلها 2. أي استنتاج منطقي (استقرار أكبر = طاقة ربط لكل نوية أكبر)؟',
  '[{"id":"A","text":"استقرار النواة يزداد كلما زادت El/A (طاقة الربط لكل نوية)","diagnostic_error":null},{"id":"B","text":"الاستقرار يزداد كلما زادت الكتلة دائمًا","diagnostic_error":"الكتلة وحدها لا تحدد الاستقرار"},{"id":"C","text":"الاستقرار يزداد كلما نقص Z","diagnostic_error":"نقصان Z ليس لحظاً للاستقرار في كل الحالات"},{"id":"D","text":"الاستقرار يتساوى لكل النوى","diagnostic_error":"El/A يتغير عبر مخطط النوى"}]'::jsonb,
  'A',
  'الاستقرار النووي يُقارن بطاقة الربط لكل نوية El/A؛ كلما كانت أكبر كانت النواة أكثر استقراراً.',
  '["nuclear_stability","binding_per_nucleon"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-049',
  'bac-physics-v2',
  'single_choice',
  'rea-modelize',
  'rea-modelize',
  'mat-logexp',
  'rea-modelize',
  3,
  'لدينا شحن مكثفة: العلاقة العامة uC(t) = E(1 − e^(−t/(RC))). ما النمذجة الصحيحة لتطور شدة التيار i(t) علماً أن i = C·duC/dt؟',
  '[{"id":"A","text":"i(t) = (E/R)·e^(−t/(RC)) (قاس من اشتقاق uC)","diagnostic_error":null},{"id":"B","text":"i(t) = (E/R)·(1 − e^(−t/(RC)))","diagnostic_error":"اعتبار i تصعد لنفس نموذج uC (خطأ منطقي)"},{"id":"C","text":"i(t) = C·E·t","diagnostic_error":"خطأ خطي بدل أسيّ (اشتقاق خاطئ)"},{"id":"D","text":"i(t) = E/R ثابتة طوال الوقت","diagnostic_error":"الاعتقاد i ثابتة (نسيان أن الشحن يتوقف)"}]'::jsonb,
  'A',
  'باشتقاق uC: duC/dt = E/(RC)·e^(−t/RC)، وبعد الضرب في C: i = (E/R)·e^(−t/RC) (تناقص أسي).',
  '["modelize_current","derive_charging"]'::jsonb,
  1
);

insert into public.diagnostic_questions
  (id, test_id, question_type, skill, primary_skill, secondary_skill, sub_skill, difficulty, question_text, options, correct_option, explanation, diagnostic_tags, weight)
values (
  'PHYV2-050',
  'bac-physics-v2',
  'single_choice',
  'rea-modelize',
  'rea-modelize',
  'mat-calc',
  'rea-modelize',
  5,
  'جسم في سقوط حر مع إهمال مقاومة الهواء: الشرط أن التسارع ثابت (a = g). اختر النموذج الرياضي الصحيح لطبيعة الحركة (بدون سرعة ابتدائية).',
  '[{"id":"A","text":"v(t) = g·t و z(t) = (1/2)g·t²","diagnostic_error":null},{"id":"B","text":"v(t) = g·t و z(t) = g·t²","diagnostic_error":"نسيان المعامل 1/2 في التكامل الثاني"},{"id":"C","text":"v(t) = ثابت و z(t) = v·t","diagnostic_error":"نموذج الحركة المنتظمة (خطأ: a=0)"},{"id":"D","text":"v(t) = v₀ + at و z(t) = v₀t + at²","diagnostic_error":"نموذج هجين صحيح جزئياً لكن بلا 1/2 على at² (تسارع ثابت لكن المعامل خاطئ)"}]'::jsonb,
  'A',
  'بتكامل a = g: v = g·t + v₀ (مع v₀ = 0)، ثم بتكامل v: z = (1/2)g·t² + z₀. النموذج الصحيح فيه المعامل 1/2.',
  '["model_free_fall","double_integration"]'::jsonb,
  1
);
