-- ============================================================
-- Migration 011: Shuffle diagnostic v2 question options.
-- Generated by scripts/build-diagnostic-v2-shuffle.js — DO NOT EDIT.
-- Absolute set: brings the migration-010 seeded rows (authored order)
-- to the canonical order defined by the shuffle script.
-- ============================================================

update public.diagnostic_questions
set options = '[{"id":"A","text":"5.2 × 10⁻⁵","diagnostic_error":null},{"id":"B","text":"5.2 × 10⁻⁴","diagnostic_error":"اتجاه تحريك الفاصلة خاطئ رقم واحد"},{"id":"C","text":"52 × 10⁻⁶","diagnostic_error":"كتابة غير علمية (الجزء قبل الفاصلة أكبر من 10)"},{"id":"D","text":"5.2 × 10⁵","diagnostic_error":"عكس اتجاه تحريك الفاصلة (أس موجب)"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-001';

update public.diagnostic_questions
set options = '[{"id":"A","text":"نانو (n)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻⁹"},{"id":"B","text":"ميلي (m)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻³"},{"id":"C","text":"ميكرو (µ)","diagnostic_error":null},{"id":"D","text":"بيكو (p)","diagnostic_error":"الخلط بين 10⁻⁶ و 10⁻¹²"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-002';

update public.diagnostic_questions
set options = '[{"id":"A","text":"800000 (8 × 10⁵)","diagnostic_error":"جمع الأسس بإشارة موجبة (3+2=5) بدل (3+(−2)=1)"},{"id":"B","text":"80","diagnostic_error":null},{"id":"C","text":"8","diagnostic_error":"نسيان ضرب الأعداد (2×4=8 صحيح لكن أخطأ في الأس)"},{"id":"D","text":"800","diagnostic_error":"خطأ في إشارة الأس عند الضرب"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-003';

update public.diagnostic_questions
set options = '[{"id":"A","text":"4 × 10⁸","diagnostic_error":null},{"id":"B","text":"16 × 10⁸","diagnostic_error":"ضرب الأعداد بدل القسمة"},{"id":"C","text":"4 × 10⁻⁸","diagnostic_error":"خطأ في إشارة الأس الناتج"},{"id":"D","text":"4 × 10⁴","diagnostic_error":"جمع الأسس بدلاً من طرحها (6−2 بدل 6+2)"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-004';

update public.diagnostic_questions
set options = '[{"id":"A","text":"259.2 m/s","diagnostic_error":"ضرب بـ 3.6 بدل القسمة"},{"id":"B","text":"36 m/s","diagnostic_error":"القسمة على 2 بدل 3.6"},{"id":"C","text":"20 m/s","diagnostic_error":null},{"id":"D","text":"72 m/s","diagnostic_error":"عدم التحويل (ترك الوحدة) والنظام غير SI"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-005';

update public.diagnostic_questions
set options = '[{"id":"A","text":"0.25 L","diagnostic_error":null},{"id":"B","text":"25 L","diagnostic_error":"الاعتقاد أن 1 L = 10 cm³"},{"id":"C","text":"2.5 L","diagnostic_error":"الخلط بين cm³ و mL"},{"id":"D","text":"250000 L","diagnostic_error":"عكس اتجاه التحويل (ضرب بـ 1000 بدل قسمته)"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-006';

update public.diagnostic_questions
set options = '[{"id":"A","text":"1.66 × 10⁹ Mg","diagnostic_error":"عكس اتجاه التحويل"},{"id":"B","text":"1.66 × 10⁻²⁷ Mg","diagnostic_error":"عدم اعتبار معامل التحويل (اعتبر kg = Mg)"},{"id":"C","text":"1.66 × 10⁻²⁴ Mg","diagnostic_error":"استعمال 10³ بدل 10⁶"},{"id":"D","text":"1.66 × 10⁻³⁰ Mg","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-007';

update public.diagnostic_questions
set options = '[{"id":"A","text":"≈ 931 × 10⁶ MeV","diagnostic_error":"عدم القسمة على 10⁶ بعد التحويل إلى eV"},{"id":"B","text":"≈ 9.31×10⁻¹⁰ MeV","diagnostic_error":"الخلط بين التحويل إلى J والتحويل إلى MeV"},{"id":"C","text":"≈ 931 MeV","diagnostic_error":null},{"id":"D","text":"≈ 9.31 MeV","diagnostic_error":"النقص بعامل 10² في الحساب"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-008';

update public.diagnostic_questions
set options = '[{"id":"A","text":"m = M / n","diagnostic_error":"قلب العلاقة (القسمة المعكوسة)"},{"id":"B","text":"m = n / M","diagnostic_error":"اعتبار n محلّى مباشرة بدون عزل"},{"id":"C","text":"m = M − n","diagnostic_error":"خلط الجبر (الجمع بدل الضرب)"},{"id":"D","text":"m = n × M","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-009';

update public.diagnostic_questions
set options = '[{"id":"A","text":"λ = t½ × ln2","diagnostic_error":"اعتبار الجداء بدل القسمة"},{"id":"B","text":"λ = ln2 / t½","diagnostic_error":null},{"id":"C","text":"λ = t½ / ln2","diagnostic_error":"قلب النسبة (البسط والمقام انعكسا)"},{"id":"D","text":"λ = ln2 × t½","diagnostic_error":"عدم إعادة (الضرب لكن بتعويض خاطئ)"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-010';

update public.diagnostic_questions
set options = '[{"id":"A","text":"F = V₁ × V₂","diagnostic_error":"جداء الحجوم بدل القسمة"},{"id":"B","text":"F = V₂ − V₁","diagnostic_error":"طرح الحجوم بدل قسمتها"},{"id":"C","text":"F = V₂ / V₁","diagnostic_error":null},{"id":"D","text":"F = V₁ / V₂","diagnostic_error":"قلب النسبة في تعويض C₁/C₂"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-011';

update public.diagnostic_questions
set options = '[{"id":"A","text":"≈ 316 m/s","diagnostic_error":"خطأ في حساب الجذر (ناقص صفر)"},{"id":"B","text":"≈ 3160 m/s","diagnostic_error":null},{"id":"C","text":"≈ 10⁷ m/s","diagnostic_error":"نسيان الجذر التربيعي"},{"id":"D","text":"≈ 100 m/s","diagnostic_error":"خطأ في قوى العدد 10 داخل المقدار"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-012';

update public.diagnostic_questions
set options = '[{"id":"A","text":"55 mol","diagnostic_error":"حساب المتبقي بدل النسبة"},{"id":"B","text":"25 mol","diagnostic_error":"اعتبار النسبة كمية مباشرة"},{"id":"C","text":"20 mol","diagnostic_error":null},{"id":"D","text":"4 mol","diagnostic_error":"قسمة 80 على 25 بدل الضرب في 0.25"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-013';

update public.diagnostic_questions
set options = '[{"id":"A","text":"75%","diagnostic_error":"اعتبار المتبقي يزداد نسبةً خطية"},{"id":"B","text":"0%","diagnostic_error":"اعتبار الانحلال خطياً (ينفد تماماً)"},{"id":"C","text":"25%","diagnostic_error":null},{"id":"D","text":"50%","diagnostic_error":"عدم تكرار التنصيف (تطبيق نصف واحد فقط)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-014';

update public.diagnostic_questions
set options = '[{"id":"A","text":"0.25","diagnostic_error":"حساب (0.4−0.3)/0.4 بدل x_f/x_max"},{"id":"B","text":"0.75","diagnostic_error":null},{"id":"C","text":"1.33","diagnostic_error":"قلب النسبة (x_max/x_f)"},{"id":"D","text":"0.3","diagnostic_error":"استعمال x_f وحده بدل النسبة"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-015';

update public.diagnostic_questions
set options = '[{"id":"A","text":"يتضاعف بنحو 2.8 (× 2√2)","diagnostic_error":null},{"id":"B","text":"لا يتغير","diagnostic_error":"تجاهل اعتماد T على r"},{"id":"C","text":"يتضاعف أربع مرات (×4)","diagnostic_error":"الخلط بين T² و T"},{"id":"D","text":"يتضاعف تماماً (×2)","diagnostic_error":"اعتبار T∝r مباشرة بدون الجذر"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-016';

update public.diagnostic_questions
set options = '[{"id":"A","text":"0 ثم 2","diagnostic_error":"عكس الموضعين (التبديل)"},{"id":"B","text":"2 ثم 0","diagnostic_error":null},{"id":"C","text":"e² ثم 1","diagnostic_error":"الخلط بين الدالة وعكسها"},{"id":"D","text":"2 ثم 1","diagnostic_error":"الاعتقاد ln(1) = 1"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-017';

update public.diagnostic_questions
set options = '[{"id":"A","text":"pH = 11","diagnostic_error":"حساب pOH بدل pH"},{"id":"B","text":"pH = 0.001","diagnostic_error":"إرجاع التركيز مباشرة دون لوغاريتم"},{"id":"C","text":"pH = 3","diagnostic_error":null},{"id":"D","text":"pH = −3","diagnostic_error":"الخلط بين pH و[H₃O⁺] بعلامة"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-018';

update public.diagnostic_questions
set options = '[{"id":"A","text":"y ≈ y₀ / 2.72 (أي ≈ 0.37 y₀)","diagnostic_error":null},{"id":"B","text":"y = 0","diagnostic_error":"اعتبار التناقص الأسّي وصولاً للصفر عند t=τ"},{"id":"C","text":"y = y₀ / 2","diagnostic_error":"الخلط مع نصف العمر (الأس × ln2)"},{"id":"D","text":"y = y₀","diagnostic_error":"اعتبار e^(−1) قريب من 1"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-019';

update public.diagnostic_questions
set options = '[{"id":"A","text":"t = ln(1/4) / λ = −ln4/λ","diagnostic_error":"علامة سالبة في البسط رغم أن t زمن موجب"},{"id":"B","text":"t = ln(4/1) · λ","diagnostic_error":"خلط بين ln والضرب في λ"},{"id":"C","text":"t = ln4 / λ","diagnostic_error":null},{"id":"D","text":"t = λ · ln4","diagnostic_error":"لا عزل صحيح (المقام والبسط انقلبا)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-020';

update public.diagnostic_questions
set options = '[{"id":"A","text":"dx/dt = 5t²/2 + 3t","diagnostic_error":"التكامل بدل الاشتقاق (قاعدة معكوسة)"},{"id":"B","text":"dx/dt = 5","diagnostic_error":null},{"id":"C","text":"dx/dt = 5t","diagnostic_error":"نسيان أن اشتقاق t يساوي 1"},{"id":"D","text":"dx/dt = 5 + 3t","diagnostic_error":"اشتقاق الثابت 3 كأنه متغير"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-021';

update public.diagnostic_questions
set options = '[{"id":"A","text":"السرعة المتوسطة على كامل التجربة","diagnostic_error":"الخلط بين السرعة اللحظية والمتوسطة"},{"id":"B","text":"السرعة اللحظية للتفاعل عند t₀ = 0.02 mol/s","diagnostic_error":null},{"id":"C","text":"زمن نصف التفاعل 0.02 s","diagnostic_error":"خلط وحدات الميل مع زمن"},{"id":"D","text":"التقدم المنجز حتى t₀ هو 0.02 mol","diagnostic_error":"خلط الميل مع قيمة x نفسها"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-022';

update public.diagnostic_questions
set options = '[{"id":"A","text":"18 m","diagnostic_error":"التكامل مع نسيان الثابت (استعمال 2t² وحده)"},{"id":"B","text":"12 m","diagnostic_error":null},{"id":"C","text":"7 m","diagnostic_error":"حساب v(3) فقط بدل المساحة"},{"id":"D","text":"6 m","diagnostic_error":"حساب مساحة مستطيل (سرعة متوسطة مفترضة)"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-023';

update public.diagnostic_questions
set options = '[{"id":"A","text":"2 m/s","diagnostic_error":"الفرق بين المركبتين (8−6)"},{"id":"B","text":"48 m/s","diagnostic_error":"الضرب قبل الجذر (6×8)"},{"id":"C","text":"14 m/s","diagnostic_error":"جمع المركبتين مباشرة (6+8)"},{"id":"D","text":"10 m/s","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-024';

update public.diagnostic_questions
set options = '[{"id":"A","text":"≈ 34.6 m/s","diagnostic_error":"ضرب خاطئ (20 × 1.73)"},{"id":"B","text":"≈ 20 m/s","diagnostic_error":"اعتبار المركبة تساوي المعيار مباشرة"},{"id":"C","text":"≈ 17.3 m/s","diagnostic_error":null},{"id":"D","text":"≈ 10 m/s","diagnostic_error":"استعمال cos60° بدل sin60° (المركبة الأفريقية)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-025';

update public.diagnostic_questions
set options = '[{"id":"A","text":"50 N","diagnostic_error":null},{"id":"B","text":"100 N","diagnostic_error":"اعتبار المركبة تساوي الوزن (زاوية 90°) للخطأ"},{"id":"C","text":"12.5 N","diagnostic_error":"جداء خاطئ (100 × 0.5 / 4)"},{"id":"D","text":"86.6 N","diagnostic_error":"استعمال cos30° بدل sin30°"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-026';

update public.diagnostic_questions
set options = '[{"id":"A","text":"12 m/s","diagnostic_error":"استعمال Δx فقط دون القسمة على Δt"},{"id":"B","text":"3 m/s","diagnostic_error":null},{"id":"C","text":"2 m/s","diagnostic_error":"خطأ حسابي في الفرق (20−8=12، ÷(6−2)=4)"},{"id":"D","text":"4 m/s","diagnostic_error":"حساب الميل كما Δx/Δt لكن أخطأ في الفرقة (8/2)"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-027';

update public.diagnostic_questions
set options = '[{"id":"A","text":"λ = −0.04 s⁻¹","diagnostic_error":"الجمع المباشر للعلامة السالبة في λ"},{"id":"B","text":"λ = e^0.04 s⁻¹","diagnostic_error":"الخلط بين ln والتجزيء"},{"id":"C","text":"λ = 1/0.04 s⁻¹","diagnostic_error":"قلب العلاقة (اعتبار tan(θ)=1/λ)"},{"id":"D","text":"λ = 0.04 s⁻¹","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-028';

update public.diagnostic_questions
set options = '[{"id":"A","text":"≈ 4.4 V","diagnostic_error":"حساب 37% بدل 63% (خلط شحن/تفريغ)"},{"id":"B","text":"≈ 7.6 V","diagnostic_error":null},{"id":"C","text":"≈ 12 V","diagnostic_error":"التوصل للقيمة النهائية فوراً (اعتبار τ = ∞)"},{"id":"D","text":"≈ 0 V","diagnostic_error":"اعتبار المكثفة فارغة عند τ"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-029';

update public.diagnostic_questions
set options = '[{"id":"A","text":"250 m","diagnostic_error":"مساحة المثلث بضرب القاعدة × الارتفاع بدون قسمة (×2)"},{"id":"B","text":"50 m","diagnostic_error":"مساحة المستطيل (القاعدة × العرض كأن v ثابتة)"},{"id":"C","text":"10 m","diagnostic_error":"استخلاص الارتفاع الواحد (v(1) فقط)"},{"id":"D","text":"125 m","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-030';

update public.diagnostic_questions
set options = '[{"id":"A","text":"السرعة تتناقص مع الزمن حتى تقارب الصفر","diagnostic_error":null},{"id":"B","text":"السرعة ثابتة طوال التفاعل","diagnostic_error":"عدم ملاحظة تناقص زيادات x"},{"id":"C","text":"السرعة تزداد مع الزمن","diagnostic_error":"خلط زيادة x مع زيادة السرعة"},{"id":"D","text":"التفاعل سريع جداً وينتهي عند t=1","diagnostic_error":"اعتبار أول خطوة كل شيء"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-031';

update public.diagnostic_questions
set options = '[{"id":"A","text":"حركة دائرية","diagnostic_error":"لا يمكن استنتاج من البيانات (إسقاط خاطئ)"},{"id":"B","text":"حركة متباطئة","diagnostic_error":"عكس الاتجاه (خلط التسارع مع التباطؤ)"},{"id":"C","text":"حركة متسارعة بانتظام","diagnostic_error":null},{"id":"D","text":"حركة منتظمة","diagnostic_error":"عدم ملاحظة تصاعد الفوارق"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-032';

update public.diagnostic_questions
set options = '[{"id":"A","text":"الهيرتز (Hz)","diagnostic_error":"الخلط بين الزمن والتردد"},{"id":"B","text":"بلا أبعاد تماماً","diagnostic_error":"الاعتقاد أنه مجرد عدد"},{"id":"C","text":"الثانية (s)","diagnostic_error":null},{"id":"D","text":"الفولت (V)","diagnostic_error":"خلط وحدات التوتر"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-033';

update public.diagnostic_questions
set options = '[{"id":"A","text":"جول (J)","diagnostic_error":"خلط وحدات الطاقة"},{"id":"B","text":"Bq","diagnostic_error":"الخلط بين النشاط وثابت التفكك"},{"id":"C","text":"s⁻¹","diagnostic_error":null},{"id":"D","text":"s","diagnostic_error":"الاعتقاد λ زمن (خلط مع τ=1/λ)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-034';

update public.diagnostic_questions
set options = '[{"id":"A","text":"kg·m/s²","diagnostic_error":"وحدة القوة نفسها (نسيان القسمة على السرعة)"},{"id":"B","text":"kg/s","diagnostic_error":null},{"id":"C","text":"بلا وحدات","diagnostic_error":"اعتبار K عدداً صرفاً"},{"id":"D","text":"kg·m/s","diagnostic_error":"قسمة على v² بدل v"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-035';

update public.diagnostic_questions
set options = '[{"id":"A","text":"3 mol/L","diagnostic_error":"جمع بدل قسمة"},{"id":"B","text":"1 mol/L","diagnostic_error":"استعمال n وحده دون القسمة على الحجم"},{"id":"C","text":"2 mol/L","diagnostic_error":"قلب النسبة (C = V/n)"},{"id":"D","text":"0.5 mol/L","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-036';

update public.diagnostic_questions
set options = '[{"id":"A","text":"n ≈ 960 mol","diagnostic_error":"عدم القسمة على R·T (حساب P·V فقط)"},{"id":"B","text":"n ≈ 1.6 mol","diagnostic_error":"استعمال درجة الحرارة بالسلسيوس دون تحويل"},{"id":"C","text":"n ≈ 1.04 × 10⁻² mol","diagnostic_error":"خطأ في العمود (ضرب T في R صحيح لكن مقام خاطئ)"},{"id":"D","text":"n ≈ 0.96 mol","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-037';

update public.diagnostic_questions
set options = '[{"id":"A","text":"100 mL","diagnostic_error":"نسيان التحويل إلى mL وعمل 0.1×20/0.05×1000"},{"id":"B","text":"10 mL","diagnostic_error":"خطأ في قلب النسبة (Vb = Ca·Cb·Va خطأ)"},{"id":"C","text":"40 mL","diagnostic_error":null},{"id":"D","text":"20 mL","diagnostic_error":"اعتبار Vb = Va (تجاهل تركيز Cb)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-038';

update public.diagnostic_questions
set options = '[{"id":"A","text":"لتسريع التفاعل وبلوغ النهاية أسرع","diagnostic_error":"عكس التأثير الحراري (البرد يبطئ لا يسرع)"},{"id":"B","text":"لإيقاف التفاعل عند اللحظة المرادة (سقي فيزيائي)","diagnostic_error":null},{"id":"C","text":"لزيادة حجم التكافؤ V_E","diagnostic_error":"الاعتقاد أن السقي يؤثر على المصير النهائي (وهو لا يؤثر)"},{"id":"D","text":"لتغيير التركيب المولي النهائي","diagnostic_error":"الخلط بين السقي والتركيز"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-039';

update public.diagnostic_questions
set options = '[{"id":"A","text":"لأن G هي نفسها σ دائماً","diagnostic_error":"الخلط بين G وσ (يصمح K)"},{"id":"B","text":"لأن σ لا علاقة لها بالتركيز","diagnostic_error":"إنكار العلاقة σ مع التراكيز"},{"id":"C","text":"لأن قياس G مستحيل عملياً","diagnostic_error":"خطأ واقعي: G تقاس بمقياس الناقلية"},{"id":"D","text":"لأن σ مستقلة عن شكل الخلية وتسمح بالحساب من التركيز عبر σ = Σλi·[Xi]","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-040';

update public.diagnostic_questions
set options = '[{"id":"A","text":"اختيار العلاقة أولاً ثم استخراج المعطيات","diagnostic_error":"اعتماد العلاقة قبل الفهم"},{"id":"B","text":"الحساب ثم المعطيات","diagnostic_error":"عكس المنهجية المعتمدة"},{"id":"C","text":"التعويض المباشر دون تحديد المطلوب","diagnostic_error":"إجراء بلا توجيه"},{"id":"D","text":"استخراج المعطيات ← تحديد المطلوب ← اختيار العلاقة ← التعويض ← التحقق","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-041';

update public.diagnostic_questions
set options = '[{"id":"A","text":"المعطيات ناقصة: نفتقد درجة الحرارة","diagnostic_error":"درجة الحرارة غير لازمة هنا"},{"id":"B","text":"المعطيات زائدة: M لا لزوم لها","diagnostic_error":"M ضرورية لحساب n"},{"id":"C","text":"المعطيات زائدة: V لا لزوم له","diagnostic_error":"V ضرورية لتحويل n إلى C"},{"id":"D","text":"اكتمل كل المطلوب: m، V، M لاستعمال n=m/M ثم C=n/V","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-042';

update public.diagnostic_questions
set options = '[{"id":"A","text":"إهمال الوحدات لأن القيم أرقام فقط","diagnostic_error":"الوحدات جوهرية للتحقق"},{"id":"B","text":"مضاعفة القيم لتسهيل الحساب","diagnostic_error":"تغيير المعطيات يخل بالنتيجة"},{"id":"C","text":"توحيد وحدات كل الكميات بالنظام الدولي (تحويل mL→L، g→kg...)","diagnostic_error":null},{"id":"D","text":"استعمال الوحدات غير الرسمية كما هي","diagnostic_error":"يؤدي غالباً لنتيجة خاطئة"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-043';

update public.diagnostic_questions
set options = '[{"id":"A","text":"الحرارة ترفع تواتر التصادمات الفعالة فتزداد السرعة وينقص t₁/₂","diagnostic_error":null},{"id":"B","text":"الحرارة لا تأثير لها إطلاقاً","diagnostic_error":"إنكار عامل حركي"},{"id":"C","text":"الحرارة تغير طبيعة التفاعل (تام بدل محدود)","diagnostic_error":"إذا كان تاماً يبقى تاماً"},{"id":"D","text":"الحرارة تستهلك المتفاعلات فتزيد كمية النواتج","diagnostic_error":"خلط العامل الحركي بالتركيب"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-044';

update public.diagnostic_questions
set options = '[{"id":"A","text":"لا انحفاظ يتطلب في التفاعلات النووية","diagnostic_error":"مبدأان دائماً محفوظان"},{"id":"B","text":"انحفاظ العدد الذري فقط","diagnostic_error":"نسيان انحفاظ A"},{"id":"C","text":"انحفاظ عدد النترونات N = A − Z","diagnostic_error":"انحفاظ A وZ لا يفرض انحفاظ N (N انعكس)"},{"id":"D","text":"انحفاظ العدد الكتلي A وانحفاظ العدد الذري Z","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-045';

update public.diagnostic_questions
set options = '[{"id":"A","text":"حركة مستقيمة متباطئة حتى السكون ثم يستقر","diagnostic_error":null},{"id":"B","text":"حركة منتظمة","diagnostic_error":"الخط ليس أفقياً وسطياً"},{"id":"C","text":"الجسم يرتد ويغير اتجاهه","diagnostic_error":"لا دليل على انعكاس الاتجاه (v تبقى ≥0)"},{"id":"D","text":"حركة متسارعة بانتظام","diagnostic_error":"الميل سالب ثابت = تباطؤ لا تسارع"}]'::jsonb, correct_option = 'A'
where id = 'PHYV2-046';

update public.diagnostic_questions
set options = '[{"id":"A","text":"B هو الأقوى","diagnostic_error":"عكس منطق المقارنة عبر Ka"},{"id":"B","text":"A هو الأقوى (Ka أكبر ⇒ تفكك أكبر ⇒ τf أكبر و pH أصغر)","diagnostic_error":null},{"id":"C","text":"متعادلان تماماً","diagnostic_error":"Ka مختلفان فهما لا يتعادلان"},{"id":"D","text":"لا يمكن الجواب بدون قياس pH","diagnostic_error":"Ka يعطي الجواب مباشرة للمقارنة"}]'::jsonb, correct_option = 'B'
where id = 'PHYV2-047';

update public.diagnostic_questions
set options = '[{"id":"A","text":"الاستقرار يتساوى لكل النوى","diagnostic_error":"El/A يتغير عبر مخطط النوى"},{"id":"B","text":"الاستقرار يزداد كلما زادت الكتلة دائمًا","diagnostic_error":"الكتلة وحدها لا تحدد الاستقرار"},{"id":"C","text":"استقرار النواة يزداد كلما زادت El/A (طاقة الربط لكل نوية)","diagnostic_error":null},{"id":"D","text":"الاستقرار يزداد كلما نقص Z","diagnostic_error":"نقصان Z ليس لحظاً للاستقرار في كل الحالات"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-048';

update public.diagnostic_questions
set options = '[{"id":"A","text":"i(t) = E/R ثابتة طوال الوقت","diagnostic_error":"الاعتقاد i ثابتة (نسيان أن الشحن يتوقف)"},{"id":"B","text":"i(t) = (E/R)·(1 − e^(−t/(RC)))","diagnostic_error":"اعتبار i تصعد لنفس نموذج uC (خطأ منطقي)"},{"id":"C","text":"i(t) = (E/R)·e^(−t/(RC)) (قاس من اشتقاق uC)","diagnostic_error":null},{"id":"D","text":"i(t) = C·E·t","diagnostic_error":"خطأ خطي بدل أسيّ (اشتقاق خاطئ)"}]'::jsonb, correct_option = 'C'
where id = 'PHYV2-049';

update public.diagnostic_questions
set options = '[{"id":"A","text":"v(t) = g·t و z(t) = g·t²","diagnostic_error":"نسيان المعامل 1/2 في التكامل الثاني"},{"id":"B","text":"v(t) = v₀ + at و z(t) = v₀t + at²","diagnostic_error":"نموذج هجين صحيح جزئياً لكن بلا 1/2 على at² (تسارع ثابت لكن المعامل خاطئ)"},{"id":"C","text":"v(t) = ثابت و z(t) = v·t","diagnostic_error":"نموذج الحركة المنتظمة (خطأ: a=0)"},{"id":"D","text":"v(t) = g·t و z(t) = (1/2)g·t²","diagnostic_error":null}]'::jsonb, correct_option = 'D'
where id = 'PHYV2-050';
